// Level 3 — Operating Accounting (m10–m14)
export default [
  {
    id: 'm10', level: 3, levelTitle: 'Operating Accounting', title: 'NIIF 15 — Reconocimiento de ingresos ★',
    standard: 'IFRS 15', tagline: 'Los ingresos se devengan cuando las promesas se cumplen: el modelo de cinco pasos que decide cuándo.',
    description: 'La NIIF 15 es la norma más examinada en el ámbito de los ingresos y un tema favorito en las entrevistas. Dominarás el modelo de cinco pasos, el reconocimiento a lo largo del tiempo frente al reconocimiento en un momento determinado, la contraprestación variable y la distinción entre activo por contrato, cuenta a cobrar y pasivo por contrato, a través de varios casos prácticos.',
    minutes: 28, skills: ['Revenue Recognition'],
    sections: [
      {
        heading: 'Por qué existe la NIIF 15',
        paragraphs: [
          'Antes de la NIIF 15, la normativa sobre ingresos estaba dispersa y era incoherente: la NIC 18 para los bienes, la NIC 11 para los contratos de construcción, más las interpretaciones. Una misma realidad económica podía dar lugar a un reconocimiento de ingresos en momentos distintos. La NIIF 15 las sustituyó a todas con un único principio: reconocer los ingresos para reflejar la transferencia de los bienes o servicios comprometidos por un importe que refleje la contraprestación a la que la entidad espera tener derecho.',
          'La idea central es el control: los ingresos se reconocen cuando (o a medida que) el cliente obtiene el control del bien o servicio, es decir, la capacidad de dirigir su uso y obtener sus beneficios. Este único criterio sustituyó la antigua prueba de los «riesgos y beneficios» y permite analizar con el mismo modelo las suscripciones de software, los proyectos de construcción y los contratos combinados de telefonía.'
        ],
        callout: { type: 'key', text: 'Un único principio: reconocer los ingresos cuando el control del bien o servicio comprometido se transfiere al cliente, por el importe que se espera recibir. Los cinco pasos sirven a esta frase.' }
      },
      {
        heading: 'El modelo de los cinco pasos',
        paragraphs: [
          'Paso 1: identificar el contrato — un acuerdo que crea derechos y obligaciones exigibles, con sustancia comercial, condiciones de pago identificables y cobro probable. Paso 2: identificar las obligaciones de desempeño — cada bien o servicio distinto comprometido. Paso 3: determinar el precio de la transacción — lo que se espera tener derecho a recibir, incluida la contraprestación variable. Paso 4: distribuir el precio entre las obligaciones según sus precios de venta independientes relativos. Paso 5: reconocer los ingresos cuando (o a medida que) se satisface cada obligación.',
          'Conviene aplicar estos pasos en orden en cada caso. La mayoría de los errores proceden de saltarse el paso 2 (agrupar cosas distintas o separar cosas que no lo son) o de reconocer ingresos en el paso 5 antes de que el control se haya transferido realmente.'
        ],
        steps: ['Identificar el contrato con el cliente.', 'Identificar las obligaciones de desempeño (bienes o servicios distintos).', 'Determinar el precio de la transacción (incluida la contraprestación variable).', 'Distribuir el precio entre las obligaciones según sus precios de venta independientes relativos.', 'Reconocer los ingresos cuando (o a medida que) se satisface cada obligación.'],
        callout: { type: 'interview', text: '«Explícame los cinco pasos». Los entrevistadores esperan la lista concisa más una frase sobre cada paso. Puntos extra por enunciar primero el principio del control y por señalar que el paso 2 (obligaciones distintas) es donde viven la mayoría de las disputas reales.' }
      },
      {
        heading: 'Obligaciones de desempeño: ¿distintas o no?',
        paragraphs: [
          'Un bien o servicio es distinto si el cliente puede beneficiarse de él por sí solo (o con recursos fácilmente disponibles) y es identificable por separado en el contrato. Un teléfono y su plan de servicio de 24 meses son dos obligaciones; una instalación que solo funciona con la máquina vendida no es distinta de la máquina.',
          'Esto importa porque cada obligación distinta recibe su propia distribución del precio y su propio momento de reconocimiento. Agrupar mal desplaza ingresos entre ejercicios — una palanca favorita de gestión del resultado y un ajuste favorito de auditoría. Paquetes de telecomunicaciones, software más implantación, equipos más mantenimiento plurianual: siempre conviene comprobar primero la distinción.'
        ],
        callout: { type: 'example', text: 'Contrato de telefonía: terminal (precio independiente 600 $) + 24 meses de servicio (30 $/mes = 720 $). Total 1.320 $ por 1.200 $ en efectivo. Dos obligaciones distintas → distribuir los 1.200 $ según los precios de venta independientes relativos: terminal 1.200 $ × 600/1.320 = 545 $ reconocidos en la entrega; servicio 655 $ reconocidos a lo largo de 24 meses.' }
      },
      {
        heading: 'A lo largo del tiempo frente a en un momento determinado',
        paragraphs: [
          'Los ingresos se reconocen a lo largo del tiempo solo si se cumple uno de estos tres criterios: (1) el cliente recibe y consume simultáneamente los beneficios (p. ej., servicios de limpieza, mantenimiento rutinario); (2) el desempeño de la entidad crea o mejora un activo que el cliente controla a medida que se crea (p. ej., construir en el terreno del cliente); o (3) el desempeño crea un activo sin uso alternativo y la entidad tiene un derecho exigible al pago por el trabajo realizado (p. ej., fabricación especializada).',
          'Si no se cumple ninguno, el reconocimiento es en un momento determinado — cuando se transfiere el control, atendiendo a indicios como el derecho al pago, el título legal, la posesión física, la transferencia de los riesgos y beneficios significativos o la aceptación del cliente. Una venta de producto estándar es en un momento determinado, en la entrega; un proyecto de construcción de dos años en el terreno del cliente es a lo largo del tiempo, normalmente por porcentaje de realización.'
        ],
        callout: { type: 'warning', text: 'Los tres criterios de reconocimiento a lo largo del tiempo son alternativos: basta con cumplir UNO. Pero «sin uso alternativo» por sí solo no basta: debe ir acompañado de un derecho exigible al pago. Si falta esa combinación, el reconocimiento de ingresos cae a un momento determinado.' },
        table: { headers: ['Escenario', 'Momento', 'Criterio'], rows: [['Servicio de limpieza mensual', 'A lo largo del tiempo', 'Recepción y consumo simultáneos'], ['Construcción en el terreno del cliente', 'A lo largo del tiempo', 'El cliente controla el activo a medida que se construye'], ['Máquina a medida, sin uso alternativo + derecho al pago', 'A lo largo del tiempo', 'Sin uso alternativo + derecho al pago'], ['Bienes estándar enviados', 'En un momento determinado', 'Control en la entrega']] }
      },
      {
        heading: 'Contraprestación variable y la restricción',
        paragraphs: [
          'Descuentos, rappels, devoluciones, bonus por desempeño y penalizaciones hacen variable el precio de la transacción. La NIIF 15 exige estimarlo — por valor esperado o por el importe más probable, según cuál prediga mejor — y aplicar después la restricción: incluir los importes variables solo en la medida en que sea altamente probable que no se produzca una reversión significativa cuando se resuelva la incertidumbre.',
          'Ejemplo: un contrato de 1.000.000 $ con un bonus por desempeño de 100.000 $ con un 60 % de probabilidad. Valor esperado 60.000 $ — pero ¿puede incluirse? Solo la parte que supere la prueba de «altamente probable que no haya reversión significativa». Si el bonus depende de factores fuera de control, cabe reconocer cero bonus hasta que se devengue. Esta restricción es deliberadamente conservadora: impide contabilizar bonus que podrían tener que revertirse.'
        ],
        callout: { type: 'example', text: 'Licencia de software 500.000 $ más cánones variables por uso estimados en 80.000 $ (valor esperado). Si el cobro del canon es altamente probable sin riesgo de reversión significativa, el precio de la transacción = 580.000 $. Si el canon depende de las volátiles ventas del cliente, hay que restringirlo: reconocer los 500.000 $ ahora y el canon a medida que sea cierto.' }
      },
      {
        heading: 'Activo por contrato frente a cuenta a cobrar frente a pasivo por contrato',
        paragraphs: [
          'Tres posiciones en el balance, tres significados distintos. Una cuenta a cobrar es un derecho incondicional a la contraprestación — solo el paso del tiempo separa el pago. Un activo por contrato es un derecho a la contraprestación condicionado a algo más — p. ej., se entregó la fase 1 pero solo se puede facturar cuando se complete la fase 2. Un pasivo por contrato es el espejo: se recibió efectivo (o se tiene un derecho incondicional a él) antes de ejecutar — los antiguos «ingresos diferidos».',
          'La distinción indica riesgo: un activo por contrato conlleva riesgo de desempeño además del riesgo de crédito, por lo que las revelaciones de las NIIF 7/9 lo tratan de forma distinta a las cuentas a cobrar. Los analistas vigilan los pasivos por contrato como indicador adelantado: unos ingresos diferidos crecientes significan que los ingresos futuros ya están financiados.'
        ],
        table: { headers: ['Partida', 'Significado', 'Ejemplo'], rows: [['Cuenta a cobrar', 'Derecho incondicional — solo falta el paso del tiempo', 'Factura emitida con vencimiento a 30 días'], ['Activo por contrato', 'Derecho condicionado a un desempeño adicional', 'Fase 1 entregada, facturable tras la fase 2'], ['Pasivo por contrato', 'Obligación de ejecutar por efectivo recibido', 'Suscripción anual cobrada por anticipado']] },
        journal: { transaction: 'Suscripción anual de software de 120.000 $ facturada y cobrada por anticipado el 1 de enero.', lines: [{ account: 'Efectivo', dr: 120000, cr: null }, { account: 'Pasivo por contrato', dr: null, cr: 120000 }], narration: 'Efectivo cobrado antes de prestar el servicio' },
        impact: { pl: 'Aún sin ingresos — 10.000 $ reconocidos mensualmente a medida que se presta el servicio.', bs: 'Efectivo +120.000 $; pasivo por contrato 120.000 $ que disminuye 10.000 $/mes.', cf: 'Entrada de efectivo operativa de 120.000 $ por anticipado.' }
      },
      {
        heading: 'Caso: contrato de construcción a lo largo del tiempo',
        paragraphs: [
          'Un contratista firma un contrato a precio fijo de 5.000.000 $ para construir un almacén en el terreno del cliente, con costes estimados de 4.000.000 $, en 2 años. El cliente controla el activo a medida que se construye (criterio 2) → ingresos a lo largo del tiempo. El progreso se mide por los costes incurridos (método de insumos): costes del año 1 de 1.600.000 $ = 40 % de avance.',
          'Año 1: ingresos 5 m $ × 40 % = 2.000.000 $; costes 1.600.000 $; beneficio 400.000 $. Se emitieron certificaciones por 1.800.000 $ y se cobraron 1.500.000 $. Los ingresos (2 m $) superan las certificaciones (1,8 m $) → activo por contrato de 200.000 $. El asiento de cada periodo es Debe Activo por contrato / Haber Ingresos ordinarios por el exceso, reclasificado a cuentas a cobrar al facturar. Si las certificaciones superan alguna vez a los ingresos, el exceso es un pasivo por contrato.'
        ],
        journal: { transaction: 'Año 1: reconocer 2.000.000 $ de ingresos con un 40 % de avance; certificaciones emitidas 1.800.000 $.', lines: [{ account: 'Activo por contrato', dr: 2000000, cr: null }, { account: 'Ingresos ordinarios', dr: null, cr: 2000000 }], narration: 'Ingresos reconocidos a lo largo del tiempo, 40 % de avance' },
        impact: { pl: 'Ingresos 2.000.000 $; costes 1.600.000 $; beneficio 400.000 $ en el año 1.', bs: 'Activo por contrato 200.000 $ (ingresos por delante de las certificaciones); cuentas a cobrar 1.800.000 $ al facturar.', cf: 'El efectivo sigue a los cobros (1.500.000 $), no a los ingresos — la entrada operativa de efectivo va por detrás del beneficio.' },
        callout: { type: 'key', text: 'El beneficio a lo largo del tiempo emerge con el progreso, pero el efectivo sigue a la facturación y al cobro. Un contratista puede mostrar beneficios sólidos con un flujo de caja operativo negativo: el activo por contrato es donde vive esa diferencia.' }
      },
      {
        heading: 'Ángulos de entrevista y señales de alerta',
        paragraphs: [
          'La NIIF 15 es un clásico de entrevista porque pone a prueba el juicio. Cabe esperar: «¿Cómo reconocerías los ingresos de una empresa SaaS?» (suscripción a lo largo del tiempo; implantación — ¿distinta o no?; cuotas variables por uso restringidas). «¿Acuerdos de venta con entrega diferida (bill-and-hold)?» (ingresos solo si se transfirió el control: el cliente lo solicitó, el producto está identificado por separado, listo para la entrega — criterios estrictos). «¿Principal frente a agente?» (ingresos brutos si se controla el bien antes de transferirlo; comisión neta si solo se intermedia).',
          'Señales de alerta para los analistas: ingresos que crecen mucho más rápido que los cobros, o pasivos por contrato que se reducen mientras los ingresos crecen (adelanto de ingresos); cambios frecuentes en las distribuciones según precios de venta independientes; picos de bill-and-hold o de saturación del canal al cierre del trimestre. Los requisitos de información a revelar de la NIIF 15 — ingresos desagregados, obligaciones de desempeño pendientes — existen precisamente para exponer estas prácticas.'
        ],
        callout: { type: 'interview', text: '«¿Principal o agente?» La prueba es el control antes de la transferencia: si se controlan los bienes antes de que lleguen al cliente, se es principal y se reconocen ingresos brutos. Si solo se intermedia la venta, se es agente y se reconoce la comisión neta. Los marketplaces viven o mueren por esta valoración.' }
      }
    ],
    mistakes: [
      'Reconocer los ingresos al cobrar en lugar de al transferir el control — el momento del efectivo es irrelevante para la NIIF 15.',
      'Tratar un paquete como una única obligación sin comprobar la distinción — el teléfono + el plan de servicio son dos obligaciones con momentos distintos.',
      'Incluir bonus totalmente variables en el precio de la transacción sin aplicar la restricción de «altamente probable que no haya reversión significativa».',
      'Confundir los activos por contrato con las cuentas a cobrar — los derechos condicionados conllevan riesgo de desempeño y distinta información a revelar.',
      'Reconocer ingresos a lo largo del tiempo sin cumplir uno de los tres criterios — por defecto es en un momento determinado.',
      'Contabilizar ingresos de bill-and-hold antes de cumplir todos los estrictos criterios de control — un truco clásico de ingresos prematuros.'
    ],
    interviewQA: [
      { q: 'Explica brevemente el modelo de los cinco pasos.', a: 'Primero, identificar el contrato — exigible, con sustancia comercial y cobro probable. Segundo, identificar las obligaciones de desempeño distintas — bienes o servicios de los que el cliente puede beneficiarse por separado. Tercero, determinar el precio de la transacción, estimando la contraprestación variable sujeta a la restricción. Cuarto, distribuir el precio según los precios de venta independientes relativos. Quinto, reconocer los ingresos cuando (o a medida que) se satisface cada obligación — a lo largo del tiempo si se cumple uno de los tres criterios, o en el momento en que se transfiere el control. Todo el modelo sirve a un principio: los ingresos reflejan la transferencia del control.' },
      { q: '¿Cuándo se reconocen los ingresos a lo largo del tiempo?', a: 'Cuando se cumple cualquiera de los tres criterios: el cliente recibe y consume simultáneamente los beneficios, como en los servicios; la entidad crea o mejora un activo que el cliente controla a medida que se crea, como al construir en el terreno del cliente; o el activo no tiene uso alternativo para la entidad y existe un derecho exigible al pago por el desempeño completado, como en la fabricación a medida. En caso contrario, el reconocimiento es en un momento determinado, juzgado por indicios como el derecho al pago, el título, la posesión y la aceptación.' },
      { q: '¿Qué diferencia hay entre un activo por contrato y una cuenta a cobrar?', a: 'Una cuenta a cobrar es un derecho incondicional a la contraprestación — solo falta el paso del tiempo antes del pago. Un activo por contrato está condicionado a algo distinto del tiempo, normalmente un desempeño adicional — por ejemplo, la fase 1 está entregada pero el contrato solo permite facturar cuando se complete la fase 2. El activo por contrato conlleva riesgo de desempeño además del riesgo de crédito, por lo que las NIIF exigen presentarlo y revelarlo por separado de las cuentas a cobrar.' },
      { q: '¿Cómo trata la NIIF 15 un bonus por desempeño que podría no devengarse?', a: 'El bonus es contraprestación variable: se estima por valor esperado o por el importe más probable y se aplica después la restricción — incluirlo solo en la medida en que sea altamente probable que su resolución posterior no provoque una reversión significativa de los ingresos. Si el bonus depende de factores inciertos o incontrolables, se reconoce cero hasta que se resuelva la incertidumbre. La restricción impide deliberadamente contabilizar ingresos que podrían tener que revertirse.' }
    ],
    quiz: [
      { question: 'El principio central de la NIIF 15 es reconocer los ingresos:', options: ['Cuando se recibe el efectivo del cliente', 'Cuando se firma el contrato', 'Cuando se emite la factura', 'Cuando el control de los bienes o servicios comprometidos se transfiere al cliente'], answer: 3, explanation: 'La NIIF 15 se construye sobre la transferencia del control, no sobre el efectivo, la firma ni la facturación. Los ingresos reflejan la transferencia por la contraprestación esperada.', difficulty: 'Foundation', topic: 'Core Principle', skill: 'Revenue Recognition' },
      { question: '¿Cuál es el orden correcto de los cinco pasos?', options: ['Identificar el contrato → identificar las obligaciones → determinar el precio → distribuir el precio → reconocer los ingresos', 'Determinar el precio → identificar el contrato → reconocer los ingresos → distribuir el precio → identificar las obligaciones', 'Identificar las obligaciones → reconocer los ingresos → determinar el precio → distribuir el precio → identificar el contrato', 'Reconocer los ingresos → identificar el contrato → determinar el precio → identificar las obligaciones → distribuir el precio'], answer: 0, explanation: 'Los pasos van en orden: contrato, obligaciones, precio, distribución, reconocimiento. Cada paso alimenta al siguiente.', difficulty: 'Foundation', topic: 'Five-Step Model', skill: 'Revenue Recognition' },
      { question: 'Un bien o servicio es distinto cuando:', options: ['Figura en una línea separada de la factura', 'El cliente puede beneficiarse de él por separado y es identificable por separado en el contrato', 'Tiene un tipo de IVA distinto', 'Se entrega en un día distinto'], answer: 1, explanation: 'La distinción exige ambas cosas: beneficio independiente (solo o con recursos disponibles) e identificabilidad separada en el contrato. La facturación o el momento de entrega por sí solos no deciden.', difficulty: 'Intermediate', topic: 'Performance Obligations', skill: 'Revenue Recognition' },
      { question: 'Los ingresos pueden reconocerse a lo largo del tiempo cuando:', options: ['El contrato dura más de un año', 'El cliente paga a plazos', 'El cliente recibe y consume simultáneamente los beneficios del desempeño', 'El valor total del contrato supera 1.000.000 $'], answer: 2, explanation: 'La recepción y el consumo simultáneos es uno de los tres criterios de reconocimiento a lo largo del tiempo. La duración, las condiciones de pago y el importe son irrelevantes.', difficulty: 'Intermediate', topic: 'Over Time', skill: 'Revenue Recognition' },
      { question: 'Un fabricante construye una máquina a medida sin uso alternativo y tiene un derecho exigible al pago por el trabajo realizado. Los ingresos se reconocen:', options: ['En un momento determinado, en la entrega final', 'A lo largo del tiempo', 'Solo cuando el efectivo está totalmente cobrado', 'Cuando se firma el contrato'], answer: 1, explanation: 'Sin uso alternativo más derecho exigible al pago cumple el tercer criterio de reconocimiento a lo largo del tiempo — los ingresos siguen al progreso, no a la entrega.', difficulty: 'Advanced', topic: 'Over Time', skill: 'Revenue Recognition' },
      { question: 'La contraprestación variable se incluye en el precio de la transacción solo en la medida en que:', options: ['La dirección sea optimista sobre devengarla', 'El cliente haya pagado una señal', 'El contrato mencione un importe máximo', 'Sea altamente probable que no se produzca una reversión significativa'], answer: 3, explanation: 'La restricción: incluir importes variables solo si es altamente improbable una reversión significativa de los ingresos cuando se resuelva la incertidumbre.', difficulty: 'Intermediate', topic: 'Variable Consideration', skill: 'Revenue Recognition' },
      { question: 'La fase 1 de un proyecto está entregada; el contrato solo permite facturar tras completar la fase 2. El derecho de 200.000 $ es un:', options: ['Activo por contrato', 'Cuenta a cobrar', 'Pasivo por contrato', 'Activo contingente'], answer: 0, explanation: 'El derecho está condicionado a un desempeño adicional (fase 2), no solo al paso del tiempo — un activo por contrato, no una cuenta a cobrar.', difficulty: 'Intermediate', topic: 'Contract Balances', skill: 'Revenue Recognition' },
      { question: 'Una suscripción anual de 120.000 $ se cobra por anticipado el 1 de enero. En ese momento la entidad reconoce:', options: ['Ingresos de 120.000 $ de inmediato', 'Una cuenta a cobrar de 120.000 $', 'Ingresos de 10.000 $ y un pasivo de 110.000 $', 'Efectivo 120.000 $ y un pasivo por contrato de 120.000 $; sin ingresos'], answer: 3, explanation: 'El efectivo antes del desempeño crea un pasivo por contrato (ingresos diferidos). Los ingresos de 10.000 $/mes siguen a medida que se presta el servicio.', difficulty: 'Intermediate', topic: 'Contract Balances', skill: 'Revenue Recognition' },
      { question: 'Contrato de 5 m $, 40 % de avance, 1,8 m $ certificados. Ingresos reconocidos y posición en el balance:', options: ['Ingresos 2.000.000 $; activo por contrato 200.000 $', 'Ingresos 1.800.000 $; sin activo por contrato', 'Ingresos 2.000.000 $; pasivo por contrato 200.000 $', 'Ingresos 5.000.000 $; cuenta a cobrar 3.200.000 $'], answer: 0, explanation: 'Ingresos = 5 m $ × 40 % = 2 m $. Ingresos por delante de las certificaciones (2 m $ − 1,8 m $) = activo por contrato 200.000 $.', difficulty: 'Advanced', topic: 'Over Time Case', skill: 'Revenue Recognition' },
      { question: 'Teléfono con precio independiente 600 $ + servicio 720 $ vendidos por 1.200 $ en efectivo. Ingresos asignados al terminal en la entrega:', options: ['600 $ (precio independiente íntegro)', '1.200 $ (precio íntegro del contrato)', '545 $ (1.200 × 600/1.320)', '480 $ (1.200 × 600/1.500)'], answer: 2, explanation: 'Distribuir según los precios de venta independientes relativos: total 1.320 $. Terminal: 1.200 $ × 600/1.320 = 545,45 $. El descuento se reparte proporcionalmente.', difficulty: 'Advanced', topic: 'Allocation', skill: 'Revenue Recognition' },
      { question: 'En un acuerdo de bill-and-hold, los ingresos pueden reconocerse antes de la entrega solo si:', options: ['El cliente ha pagado íntegramente', 'Se cumplen criterios estrictos, incluidos la solicitud del cliente, la identificación separada y la disponibilidad para la transferencia', 'Los bienes están fabricados', 'El equipo de ventas necesita cumplir su objetivo'], answer: 1, explanation: 'El bill-and-hold exige todos los criterios estrictos: motivo sustantivo (solicitud del cliente), producto identificado por separado, listo para la transferencia física, y sin posibilidad de usarlo ni redirigirlo.', difficulty: 'Advanced', topic: 'Point in Time', skill: 'Revenue Recognition' },
      { question: 'Un marketplace intermedia ventas entre compradores y vendedores sin controlar nunca los bienes. Es:', options: ['Un principal que reconoce las ventas brutas como ingresos', 'Sin reconocer ningún ingreso', 'Reconociendo el precio íntegro de la venta como ingresos', 'Un agente que reconoce la comisión neta como ingresos'], answer: 3, explanation: 'Sin control antes de la transferencia, el marketplace es un agente: los ingresos son la comisión neta, no el valor bruto de la transacción.', difficulty: 'Advanced', topic: 'Principal vs Agent', skill: 'Revenue Recognition' }
    ]
  },
  {
    id: 'm11', level: 3, levelTitle: 'Operating Accounting', title: 'NIC 2 — Existencias',
    standard: 'IAS 2', tagline: 'Las existencias en el almacén solo valen lo que se pueda vender: coste frente a valor neto realizable.',
    description: 'La NIC 2 regula la valoración de las existencias: fórmulas de coste, la regla del menor entre coste y valor neto realizable, y los deterioros. Trabajarás el caso completo del VNR, aprenderás cuándo se permiten las reversiones y verás cómo las decisiones sobre existencias mueven el margen bruto.',
    minutes: 18, skills: ['IFRS Fundamentals'],
    sections: [
      {
        heading: 'Qué cuenta como existencias — y a qué coste',
        paragraphs: [
          'Las existencias son activos poseídos para ser vendidos en el curso normal de la explotación, en proceso de producción con vistas a esa venta, o en forma de materiales para ser consumidos en la producción. El coste incluye el precio de compra, los costes de transformación (mano de obra directa, gastos generales de producción) y otros costes para darles su condición y ubicación actuales. Los desperdicios anormales, los costes de almacenamiento posteriores a la producción y los costes de venta están excluidos — van directamente a la cuenta de resultados.',
          'Los gastos generales fijos de producción se distribuyen según la capacidad normal, no la producción real. En un mes de baja producción, los gastos generales no distribuidos se llevan a gastos, no se entierran en las existencias — esto impide que las empresas inflen las existencias (y el beneficio) produciendo poco. Es una de las discretas normas antimanipulación de la NIC 2.'
        ],
        callout: { type: 'key', text: 'Coste de las existencias = compra + transformación + costes para darles su condición y ubicación actuales. Los desperdicios anormales y el almacenamiento posterior a la producción se llevan a gastos de inmediato — nunca se capitalizan.' }
      },
      {
        heading: 'Fórmulas de coste: solo FIFO y coste medio ponderado',
        paragraphs: [
          'La NIC 2 permite las fórmulas FIFO y coste medio ponderado; el LIFO está prohibido (recuerda el m05). La fórmula elegida debe aplicarse de forma coherente a todas las existencias de naturaleza similar. Para partidas intercambiables no se permite la identificación específica — no se puede elegir qué unidades «se vendieron» para gestionar los márgenes.',
          'Con precios al alza, FIFO presenta un coste de ventas menor y un beneficio mayor que el coste medio (los costes más antiguos y baratos salen primero), dejando los costes más nuevos y altos en las existencias. La elección es una política contable según la NIC 8: solo se cambia si la nueva fórmula aporta información más relevante, con aplicación retroactiva.'
        ],
        callout: { type: 'example', text: 'Se compran 100 unidades a 10 $ y luego 100 a 14 $. Se venden 100 unidades. Coste de ventas FIFO = 1.000 $ (las unidades de 10 $); coste medio = 1.200 $. El beneficio FIFO es 200 $ mayor y las existencias finales 200 $ mayores — misma economía, distinto beneficio.' }
      },
      {
        heading: 'La prueba del VNR: menor entre coste y valor neto realizable',
        paragraphs: [
          'Las existencias se valoran al menor entre el coste y el valor neto realizable. El VNR es el precio de venta estimado menos los costes estimados para terminar la producción y los costes de venta — lo que las existencias realizarán realmente, no lo que se espera. Cuando el VNR cae por debajo del coste — obsolescencia, daños, caída de precios de mercado — las existencias se deterioran, y el deterioro se reconoce como gasto en el periodo en que se produce.',
          'La prueba se aplica partida por partida (o a grupos de partidas similares), no al total de las existencias — no se puede esconder una línea de producto muerta detrás de una rentable. Los materiales para la producción no se deterioran por debajo del coste si se espera que los productos terminados a los que se incorporarán se vendan por encima del coste.'
        ],
        callout: { type: 'warning', text: 'El VNR mira al futuro: precio de venta estimado menos costes para terminar y vender. Usar el precio de catálogo actual sin deducir los costes de venta sobrestima el VNR e infravalora el deterioro.' }
      },
      {
        heading: 'Caso práctico: coste 100, VNR 82',
        paragraphs: [
          'Una línea de producto tiene un coste en libros de 100.000 $. Los precios de mercado han caído: el precio de venta estimado es 95.000 $, con 8.000 $ de costes para terminar y 5.000 $ de costes de venta. VNR = 95.000 $ − 8.000 $ − 5.000 $ = 82.000 $. Como el VNR (82.000 $) está por debajo del coste (100.000 $), se requiere un deterioro de 18.000 $.',
          'El asiento es Debe Coste de ventas (o gasto por deterioro de existencias) 18.000 $, Haber Existencias 18.000 $. La cuenta de resultados asume el golpe ahora — la prudencia exige reconocer la pérdida en cuanto es evidente, no esperar a la venta. El balance lleva las existencias a 82.000 $, su importe recuperable.'
        ],
        journal: { transaction: 'Existencias con coste de 100.000 $ y VNR de 82.000 $; deterioro hasta el VNR.', lines: [{ account: 'Coste de ventas — Deterioro de existencias', dr: 18000, cr: null }, { account: 'Existencias', dr: null, cr: 18000 }], narration: 'Deterioro de existencias hasta el valor neto realizable' },
        impact: { pl: 'Gasto de 18.000 $ reconocido de inmediato; el margen bruto cae 18.000 $.', bs: 'Existencias valoradas a 82.000 $ en lugar de 100.000 $; patrimonio neto −18.000 $.', cf: 'Sin efecto en el efectivo — la pérdida no está realizada hasta la venta.' },
        callout: { type: 'key', text: 'Deterioro = Coste − VNR = 100.000 $ − 82.000 $ = 18.000 $. Reconocido de inmediato como gasto. Esperar a la venta para reconocer la pérdida vulnera la NIC 2.' }
      },
      {
        heading: 'Reversiones: permitidas cuando mejoran las condiciones',
        paragraphs: [
          'A diferencia de muchos deterioros, los deterioros de existencias de la NIC 2 SÍ pueden revertirse. Si las circunstancias que causaron el deterioro dejan de existir — se recuperan los precios de mercado — la reversión se reconoce como una reducción del coste de ventas en el periodo de la reversión, limitada al importe del deterioro original. Las existencias nunca pueden quedar valoradas por encima de su coste original mediante una reversión.',
          'Continuando el caso: si el VNR se recupera después hasta 95.000 $, se revierten 13.000 $ (hasta los 18.000 $ deteriorados): Debe Existencias 13.000 $, Haber Coste de ventas 13.000 $. El techo es el coste (100.000 $) — las reversiones restauran, nunca revalúan al alza. Esta asimetría (deteriorar de inmediato, revertir solo con evidencia) es la prudencia en acción.'
        ],
        callout: { type: 'interview', text: '«¿Pueden revertirse los deterioros de existencias según las NIIF?» Sí — a diferencia de los deterioros del fondo de comercio. La reversión se reconoce en el periodo en que mejoran las condiciones, con el límite del deterioro original, de modo que las existencias nunca superen el coste. Los US GAAP también prohíben las reversiones en existencias, así que esta es otra diferencia real NIIF/US GAAP.' }
      }
    ],
    mistakes: [
      'Usar el precio de venta como VNR sin deducir los costes para terminar la producción y los costes de venta.',
      'Comprobar el VNR sobre el total de las existencias en lugar de partida por partida, escondiendo líneas obsoletas detrás de las rentables.',
      'Capitalizar desperdicios anormales o almacenamiento posterior a la producción en el coste de las existencias.',
      'Usar LIFO para las existencias — prohibido según las NIIF.',
      'Revertir un deterioro por encima del coste original — las reversiones solo pueden restaurar, nunca revaluar al alza.',
      'Retrasar el deterioro hasta que se venden los bienes — la pérdida se reconoce cuando el VNR cae por debajo del coste.'
    ],
    interviewQA: [
      { q: 'Las existencias cuestan 100.000 $ y el VNR es 82.000 $. Explícamelo.', a: 'La NIC 2 exige el menor entre coste y VNR, así que se reconoce un deterioro de 18.000 $ de inmediato: Debe Coste de ventas 18.000 $, Haber Existencias 18.000 $. El margen bruto cae 18.000 $ este periodo y las existencias quedan valoradas a 82.000 $. No hay efecto en el efectivo todavía. Si el VNR se recupera después, el deterioro puede revertirse hasta los 18.000 $ originales — pero las existencias nunca pueden quedar por encima de su coste de 100.000 $.' },
      { q: '¿Qué se incluye en el coste de las existencias y qué se excluye?', a: 'Incluido: precio de compra neto de descuentos, costes de transformación (mano de obra directa y gastos generales de producción distribuidos según la capacidad normal) y otros costes para darles su condición y ubicación actuales. Excluido: desperdicios anormales, almacenamiento posterior a la producción, gastos generales administrativos y costes de venta — todos llevados a gastos de inmediato. La regla de la capacidad normal impide que las empresas inflen las existencias distribuyendo gastos generales fijos sobre producciones minúsculas.' },
      { q: '¿Cómo afecta al beneficio la elección de la fórmula de coste en inflación?', a: 'Con precios al alza, FIFO carga en el coste de ventas los costes más antiguos (más baratos), así que FIFO presenta un margen bruto mayor y unas existencias finales mayores que el coste medio. La elección es una política contable de la NIC 8: se aplica de forma coherente y solo se cambia por información más relevante con reexpresión retroactiva. Y el LIFO, que mostraría el beneficio más bajo en inflación, está prohibido según las NIIF.' }
    ],
    quiz: [
      { question: 'Existencias con coste de 100.000 $; precio de venta estimado 95.000 $; costes para terminar 8.000 $; costes de venta 5.000 $. ¿VNR y deterioro?', options: ['VNR 82.000 $; deterioro 18.000 $', 'VNR 95.000 $; deterioro 5.000 $', 'VNR 87.000 $; deterioro 13.000 $', 'VNR 100.000 $; sin deterioro'], answer: 0, explanation: 'VNR = 95.000 $ − 8.000 $ − 5.000 $ = 82.000 $. Deterioro = 100.000 $ − 82.000 $ = 18.000 $.', difficulty: 'Intermediate', topic: 'NRV', skill: 'IFRS Fundamentals' },
      { question: 'El asiento del deterioro de 18.000 $ es:', options: ['Debe Existencias 18.000 $; Haber Coste de ventas 18.000 $', 'Debe Coste de ventas 18.000 $; Haber Existencias 18.000 $', 'Debe Efectivo 18.000 $; Haber Existencias 18.000 $', 'Debe Reservas 18.000 $; Haber Existencias 18.000 $'], answer: 1, explanation: 'El deterioro es un gasto reconocido de inmediato (normalmente en el coste de ventas), que reduce el valor en libros de las existencias.', difficulty: 'Foundation', topic: 'Journal Entries', skill: 'IFRS Fundamentals' },
      { question: 'Si el VNR se recupera después hasta 95.000 $, la reversión es:', options: ['18.000 $ abonados a ingresos', '5.000 $ cargados a existencias', '13.000 $ abonados al coste de ventas (las existencias no pueden superar el coste)', 'No se permite ninguna reversión'], answer: 2, explanation: 'Reversión = 95.000 $ − 82.000 $ = 13.000 $, reconocida como reducción del coste de ventas. El techo del coste de 100.000 $ la limita.', difficulty: 'Advanced', topic: 'Reversals', skill: 'IFRS Fundamentals' },
      { question: '¿Qué fórmula de coste prohíbe la NIC 2?', options: ['FIFO', 'Coste medio ponderado', 'Identificación específica para partidas no intercambiables', 'LIFO'], answer: 3, explanation: 'La NIC 2 prohíbe el LIFO. FIFO y el coste medio están permitidos; la identificación específica se exige para partidas no intercambiables.', difficulty: 'Foundation', topic: 'Cost Formulas', skill: 'IFRS Fundamentals' },
      { question: '¿Qué coste debe excluirse de las existencias?', options: ['Mano de obra directa', 'Desperdicios anormales en la producción', 'Gastos generales de producción a capacidad normal', 'Fletes de entrada al almacén'], answer: 1, explanation: 'Los desperdicios anormales se llevan a gastos de inmediato. La mano de obra directa, los gastos generales a capacidad normal y los fletes de entrada forman parte del coste.', difficulty: 'Intermediate', topic: 'Cost Components', skill: 'IFRS Fundamentals' },
      { question: 'Los gastos generales fijos de producción se distribuyen según:', options: ['La producción real del periodo', 'La capacidad teórica máxima', 'La capacidad normal', 'La previsión de la dirección'], answer: 2, explanation: 'La capacidad normal impide inflar las existencias (y el beneficio) en periodos de baja producción; los gastos generales no distribuidos se llevan a gastos.', difficulty: 'Intermediate', topic: 'Cost Components', skill: 'IFRS Fundamentals' },
      { question: 'La prueba del VNR se aplica:', options: ['Partida por partida (o grupos de partidas similares)', 'Al total de las existencias como un único número', 'Solo a los productos terminados', 'Solo al cierre del ejercicio, nunca en periodos intermedios'], answer: 0, explanation: 'Partida por partida (o grupos similares) para que las líneas obsoletas no se escondan detrás de las rentables. Se aplica siempre que existan indicios.', difficulty: 'Intermediate', topic: 'NRV', skill: 'IFRS Fundamentals' },
      { question: 'En un periodo de precios al alza, frente al coste medio, FIFO presenta:', options: ['Mayor beneficio y mayores existencias finales', 'Menor beneficio y menores existencias finales', 'Mayor beneficio y menores existencias finales', 'El mismo beneficio — la fórmula no importa'], answer: 0, explanation: 'FIFO lleva a gastos los costes más antiguos y baratos primero → menor coste de ventas → mayor beneficio; los costes más nuevos y caros quedan en las existencias.', difficulty: 'Advanced', topic: 'Cost Formulas', skill: 'Financial Analysis' },
      { question: 'Los materiales para la producción se deterioran por debajo del coste cuando:', options: ['Cae su coste de reposición, con independencia de los productos terminados', 'La dirección lo decide', 'Se espera que los productos terminados a los que se incorporarán se vendan por debajo del coste', 'Nunca — los materiales siempre van al coste'], answer: 2, explanation: 'Los materiales siguen a los productos terminados: solo se deterioran si el VNR del producto terminado está por debajo de su coste. La caída del coste de reposición por sí sola no basta.', difficulty: 'Advanced', topic: 'NRV', skill: 'IFRS Fundamentals' }
    ]
  },
  {
    id: 'm12', level: 3, levelTitle: 'Operating Accounting', title: 'NIC 16 — Inmovilizado material',
    standard: 'IAS 16', tagline: 'Grandes máquinas, vidas largas: cómo el coste se convierte en amortización, componentes y revalorizaciones.',
    description: 'La NIC 16 trata los activos tangibles de vida larga: el coste inicial, el ejercicio de la amortización, la contabilidad por componentes y la elección entre el modelo del coste y el de revalorización. Calcularás la amortización desde los primeros principios y aprenderás por qué las partes significativas se amortizan por separado.',
    minutes: 20, skills: ['IFRS Fundamentals'],
    sections: [
      {
        heading: 'Reconocimiento y coste inicial',
        paragraphs: [
          'El inmovilizado material se reconoce cuando es probable que fluyan a la entidad beneficios económicos futuros y el coste puede medirse con fiabilidad. El coste inicial es todo lo necesario para dejar el activo en condiciones de funcionamiento: precio de compra, aranceles de importación, instalación, honorarios profesionales y el coste estimado de desmantelamiento y restauración del emplazamiento (reconocido con la correspondiente provisión según la NIC 37).',
          'Los costes por préstamos en activos aptos se capitalizan según la NIC 23. Lo que nunca se incluye: los gastos generales administrativos, los costes de formación y los costes de apertura de una nueva instalación — esos van a gastos. La disciplina es la misma que en la NIC 2: capitalizar lo que crea el beneficio futuro del activo, llevar a gastos el resto.'
        ],
        callout: { type: 'key', text: 'Coste = todo el desembolso para dejar el activo listo para su uso, incluidas las provisiones por desmantelamiento. El mantenimiento diario se lleva a gastos; solo se capitalizan las sustituciones de partes que cumplan los criterios de reconocimiento.' }
      },
      {
        heading: 'Amortización: el ejercicio central',
        paragraphs: [
          'La amortización distribuye el importe amortizable (coste menos valor residual) a lo largo de la vida útil. El valor residual es lo que se espera que valga el activo al final de su vida; la vida útil es el periodo durante el que la entidad espera usarlo — no el máximo físico del activo. Ambos son estimaciones, revisadas al menos anualmente.',
          'Ejercicio práctico: máquina con coste de 120.000 $, vida útil de 5 años, valor residual de 20.000 $. Importe amortizable = 120.000 $ − 20.000 $ = 100.000 $. Amortización anual lineal = 100.000 $ ÷ 5 = 20.000 $. Cada año: Debe Amortización del inmovilizado 20.000 $, Haber Amortización acumulada 20.000 $. Tras 3 años el valor en libros es 120.000 $ − 60.000 $ = 60.000 $.'
        ],
        journal: { transaction: 'Amortización anual de la máquina: coste 120.000 $, residual 20.000 $, vida de 5 años.', lines: [{ account: 'Amortización del inmovilizado', dr: 20000, cr: null }, { account: 'Amortización acumulada — Maquinaria', dr: null, cr: 20000 }], narration: 'Amortización lineal, año 1 de 5' },
        impact: { pl: 'Gasto por amortización de 20.000 $ al año que reduce el beneficio.', bs: 'El valor en libros cae 20.000 $/año: 100.000 $ tras el año 1 … 20.000 $ (residual) tras el año 5.', cf: 'Sin efecto en el efectivo — la amortización es una distribución no monetaria.' },
        callout: { type: 'example', text: 'Importe amortizable = 120.000 $ − 20.000 $ = 100.000 $. Cuota anual = 100.000 $ ÷ 5 = 20.000 $. Olvidar restar el valor residual es el error de examen más común — aquí sobrestima la amortización en 4.000 $/año.' }
      },
      {
        heading: 'Contabilidad por componentes',
        paragraphs: [
          'La NIC 16 exige amortizar por separado cada parte significativa de un activo. El fuselaje (25 años), los motores (10 años) y el interior (5 años) de un avión son tres componentes con tres planes de amortización. Tratar el avión como un único activo de 25 años infravaloraría la amortización inicial y sobrestimaría el beneficio.',
          'La componentización también rige las sustituciones: cuando se sustituye un motor, se da de baja el valor en libros del motor antiguo y el nuevo se capitaliza como su propio componente. Las grandes inspecciones (p. ej., la revisión en dique seco de un buque) pueden capitalizarse como un componente y amortizarse hasta la siguiente inspección. Aquí es donde la NIC 16 se vuelve práctica — y donde los auditores comprueban si las «reparaciones» son en realidad sustituciones.'
        ],
        callout: { type: 'warning', text: 'Capitalizar una reparación rutinaria como «sustitución de componente» infla los activos y el beneficio. La prueba: ¿el desembolso sustituye un componente previamente reconocido o cumple por sí solo los criterios de reconocimiento? El mantenimiento diario nunca cualifica.' }
      },
      {
        heading: 'Modelo del coste frente a modelo de revalorización',
        paragraphs: [
          'Tras el reconocimiento, la NIC 16 ofrece una elección de política por clase de inmovilizado: el modelo del coste (coste menos amortización y deterioro) o el modelo de revalorización (valor razonable en la fecha de revalorización menos amortización y deterioro posteriores). Las revalorizaciones deben ser lo bastante regulares para que el valor en libros no difiera materialmente del valor razonable.',
          'Los aumentos por revalorización van a otro resultado global (superávit de revalorización en el patrimonio neto), no al beneficio — salvo que reviertan una disminución anterior llevada a resultados. Las disminuciones van a resultados salvo que exista superávit para ese activo. Esta asimetría refleja la prudencia: las ganancias se aparcan en el patrimonio neto hasta realizarse; las pérdidas van de inmediato a resultados. Al enajenar, el superávit se traspasa a reservas (nunca a través de resultados).'
        ],
        journal: { transaction: 'Edificio revalorizado al alza: valor en libros 800.000 $, valor razonable 950.000 $.', lines: [{ account: 'Edificios', dr: 150000, cr: null }, { account: 'Superávit de revalorización (otro resultado global)', dr: null, cr: 150000 }], narration: 'Aumento por revalorización reconocido en otro resultado global' },
        impact: { pl: 'Sin efecto en el beneficio en la revalorización al alza (va a otro resultado global).', bs: 'Inmovilizado material +150.000 $; superávit de revalorización (patrimonio neto) +150.000 $.', cf: 'Sin efecto en el efectivo.' },
        callout: { type: 'interview', text: '«¿Por qué elegiría una empresa el modelo de revalorización?» Para mostrar un balance más actual — relevante en empresas intensivas en activos que buscan financiación. Los costes: valoraciones periódicas, volatilidad en el patrimonio neto y mayor amortización futura. La mayoría se queda en el coste por simplicidad.' }
      },
      {
        heading: 'Baja y disciplina de revisión',
        paragraphs: [
          'Un activo se da de baja al enajenarlo o cuando no se esperan beneficios futuros. Ganancia o pérdida = precio de venta menos valor en libros, reconocida en la cuenta de resultados. Un activo totalmente amortizado que sigue en uso permanece en libros al coste menos la amortización acumulada (valor en libros = valor residual) — no se da de baja solo porque terminó la amortización.',
          'Las vidas útiles, los valores residuales y los métodos de amortización se revisan al menos cada cierre; los cambios son cambios de estimación según la NIC 8 — prospectivos. Y todo activo está sujeto a la prueba de deterioro de la NIC 36 cuando existen indicios (m14). Amortización, revalorización y deterioro juntos mantienen honestos los valores en libros entre valoraciones.'
        ],
        bullets: ['Ganancia/pérdida en la enajenación = precio de venta − valor en libros → cuenta de resultados.', 'Los activos totalmente amortizados en uso siguen reconocidos; la amortización simplemente se detiene en el valor residual.', 'Vida, residual y método se revisan anualmente — los cambios son cambios de estimación prospectivos.', 'Los indicios de deterioro activan la prueba de la NIC 36 con independencia del plan de amortización.']
      }
    ],
    mistakes: [
      'Calcular la amortización sobre el coste íntegro sin restar el valor residual — el importe amortizable es el coste menos el residual.',
      'Amortizar el terreno — el terreno normalmente tiene vida indefinida y no se amortiza (solo se amortizan los edificios sobre él).',
      'Llevar a gastos una sustitución de componente que debería capitalizarse, o capitalizar un mantenimiento rutinario que debería ir a gastos.',
      'Abonar las ganancias por revalorización al beneficio — las revalorizaciones al alza van a otro resultado global (superávit de revalorización), no al beneficio.',
      'Continuar la amortización por debajo del valor residual — la amortización se detiene cuando el valor en libros alcanza el residual.',
      'Tratar un cambio en la vida útil como un cambio de política — es un cambio de estimación, aplicado de forma prospectiva.'
    ],
    interviewQA: [
      { q: 'Máquina con coste de 120.000 $, vida útil de 5 años, residual de 20.000 $. ¿Cuál es la amortización anual?', a: 'El importe amortizable es el coste menos el residual: 120.000 $ − 20.000 $ = 100.000 $. En línea recta a 5 años da 20.000 $ al año: Debe Amortización del inmovilizado 20.000 $, Haber Amortización acumulada 20.000 $. Tras 3 años el valor en libros es 60.000 $. El error más común es amortizar los 120.000 $ íntegros, lo que sobrestima la cuota en 4.000 $ al año.' },
      { q: 'Explica la contabilidad por componentes con un ejemplo.', a: 'La NIC 16 exige amortizar por separado las partes significativas con vidas útiles distintas. Un avión: fuselaje 25 años, motores 10 años, interior de cabina 5 años — tres componentes, tres planes. Cuando se sustituye un motor, se da de baja el valor en libros del motor antiguo y el nuevo se capitaliza. Sin componentización, una única vida de 25 años infravaloraría la amortización inicial y sobrestimaría el beneficio.' },
      { q: '¿Dónde van las ganancias y pérdidas por revalorización?', a: 'Las revalorizaciones al alza van a otro resultado global, acumulándose en el superávit de revalorización dentro del patrimonio neto — no al beneficio. Las revalorizaciones a la baja van a la cuenta de resultados, salvo que reviertan un superávit previo del mismo activo, en cuyo caso reducen primero el superávit. Al enajenar, el superávit se traspasa directamente a reservas, nunca a través de la cuenta de resultados.' }
    ],
    quiz: [
      { question: 'Coste 120.000 $, vida útil 5 años, valor residual 20.000 $. ¿Amortización anual lineal?', options: ['24.000 $', '20.000 $', '16.000 $', '4.000 $'], answer: 1, explanation: '(120.000 $ − 20.000 $) ÷ 5 = 20.000 $. Primero hay que restar el valor residual.', difficulty: 'Foundation', topic: 'Depreciation', skill: 'IFRS Fundamentals' },
      { question: 'Tras 3 años, ¿cuál es el valor en libros de la máquina?', options: ['48.000 $', '72.000 $', '20.000 $', '60.000 $'], answer: 3, explanation: '120.000 $ − (3 × 20.000 $) = 60.000 $. La amortización acumulada es 60.000 $.', difficulty: 'Intermediate', topic: 'Depreciation', skill: 'IFRS Fundamentals' },
      { question: '¿Qué coste se incluye en el coste inicial del inmovilizado material?', options: ['La formación del personal en la nueva máquina', 'Los gastos generales administrativos', 'La publicidad del producto que fabricará', 'Los costes estimados de desmantelamiento y restauración del emplazamiento'], answer: 3, explanation: 'El desmantelamiento/la restauración forman parte del coste (con la correspondiente provisión). La formación, la administración y la publicidad se llevan a gastos.', difficulty: 'Intermediate', topic: 'Initial Cost', skill: 'IFRS Fundamentals' },
      { question: 'Los motores de un avión (vida de 10 años) dentro de un fuselaje de 25 años deben:', options: ['Amortizarse por separado como componente significativo', 'Amortizarse a 25 años con el fuselaje', 'Llevarse a gastos de inmediato', 'Tratarse como existencias'], answer: 0, explanation: 'La NIC 16 exige componentizar las partes significativas con vidas distintas y amortizarlas por separado.', difficulty: 'Intermediate', topic: 'Components', skill: 'IFRS Fundamentals' },
      { question: 'Según el modelo de revalorización, una revalorización al alza se reconoce en:', options: ['La cuenta de resultados como ganancia', 'Otro resultado global (superávit de revalorización)', 'Ingresos ordinarios', 'Reservas directamente'], answer: 1, explanation: 'Las revalorizaciones al alza van a otro resultado global y se acumulan en el superávit de revalorización del patrimonio neto — nunca al beneficio (salvo que reviertan una disminución previa llevada a resultados).', difficulty: 'Intermediate', topic: 'Revaluation', skill: 'IFRS Fundamentals' },
      { question: 'Una revalorización a la baja sin superávit existente para el activo se reconoce en:', options: ['Otro resultado global', 'Reservas directamente', 'La cuenta de resultados', 'No se reconoce'], answer: 2, explanation: 'Sin superávit que la absorba, la disminución va de inmediato a la cuenta de resultados.', difficulty: 'Intermediate', topic: 'Revaluation', skill: 'IFRS Fundamentals' },
      { question: '¿Qué activo NO se amortiza normalmente?', options: ['Edificios', 'Maquinaria', 'Vehículos', 'Terrenos'], answer: 3, explanation: 'El terreno normalmente tiene vida útil indefinida y no se amortiza; los edificios, la maquinaria y los vehículos sí.', difficulty: 'Foundation', topic: 'Depreciation', skill: 'IFRS Fundamentals' },
      { question: 'Un cambio en la vida útil de un activo se contabiliza como:', options: ['Un cambio de estimación, aplicado de forma prospectiva', 'Un cambio de política, aplicado de forma retroactiva', 'Un error de ejercicios anteriores', 'No puede cambiarse'], answer: 0, explanation: 'La vida útil es una estimación; las revisiones se aplican de forma prospectiva según la NIC 8 — cambian la amortización actual y futura, el historial queda intacto.', difficulty: 'Advanced', topic: 'Estimates', skill: 'IFRS Fundamentals' },
      { question: 'Una máquina valorada en 60.000 $ se vende por 72.000 $. La ganancia reconocida es:', options: ['72.000 $ en la cuenta de resultados', '12.000 $ en otro resultado global', '12.000 $ en la cuenta de resultados', '60.000 $ en reservas'], answer: 2, explanation: 'Ganancia = precio 72.000 $ − valor en libros 60.000 $ = 12.000 $, reconocida en la cuenta de resultados al dar de baja.', difficulty: 'Intermediate', topic: 'Derecognition', skill: 'IFRS Fundamentals' }
    ]
  },
  {
    id: 'm13', level: 3, levelTitle: 'Operating Accounting', title: 'NIC 38 — Activos intangibles',
    standard: 'IAS 38', tagline: 'Ideas en el balance: cuándo la I+D se convierte en activo y cuándo queda en gasto.',
    description: 'La NIC 38 traza la línea más dura de la contabilidad operativa: la investigación siempre se lleva a gastos, el desarrollo solo se capitaliza si se cumplen los seis criterios. Aprenderás las seis pruebas, las reglas de amortización y por qué los intangibles de vida indefinida eluden la amortización para someterse a pruebas anuales de deterioro.',
    minutes: 16, skills: ['IFRS Fundamentals'],
    sections: [
      {
        heading: '¿Qué es un activo intangible?',
        paragraphs: [
          'Un activo intangible es un activo identificable, de carácter no monetario y sin apariencia física: patentes, software, licencias, relaciones con clientes, marcas (si son adquiridas). Identificable significa separable (podría venderse o licenciarse por sí solo) o que surge de derechos contractuales o legales. Una plantilla cualificada no es identificable — no puede separarse del negocio — así que nunca es un activo intangible.',
          'El reconocimiento exige la prueba habitual: beneficios futuros probables y coste medible con fiabilidad. La gran división práctica es cómo surgió el activo: los intangibles adquiridos son directos (el coste es el precio pagado); los generados internamente se enfrentan al calvario de investigación frente a desarrollo que sigue. Y una regla absoluta: el fondo de comercio generado internamente, las marcas, las cabeceras de publicaciones y las listas de clientes nunca se reconocen — su coste no puede distinguirse del desarrollo del negocio en su conjunto.'
        ],
        callout: { type: 'key', text: 'Marcas, fondo de comercio, cabeceras y listas de clientes generados internamente: NUNCA se reconocen como activos según la NIC 38. Solo llegan al balance los intangibles adquiridos y los costes de desarrollo que cualifiquen.' }
      },
      {
        heading: 'Investigación frente a desarrollo: los seis criterios',
        paragraphs: [
          'La investigación — indagación original para obtener nuevo conocimiento — siempre se lleva a gastos. Sin excepciones. El desarrollo — aplicar la investigación a un plan de nuevos productos o procesos — se capitaliza si y solo si se cumplen TODOS los seis criterios: (1) viabilidad técnica para completarlo, (2) intención de completarlo y usarlo o venderlo, (3) capacidad para usarlo o venderlo, (4) probables beneficios económicos futuros (existe un mercado), (5) recursos técnicos, financieros y de otro tipo adecuados para completarlo, y (6) medición fiable del desembolso.',
          'Si falla aunque sea uno, todo queda en la cuenta de resultados. Los criterios son deliberadamente estrictos porque capitalizar el desarrollo embellece el beneficio — los auditores comprueban cada uno, sobre todo la viabilidad técnica y la existencia de un mercado. Una vez capitalizado, la amortización comienza cuando el activo está disponible para su uso, no cuando empieza el proyecto.'
        ],
        callout: { type: 'warning', text: 'Los SEIS criterios, no «la mayoría». Un proyecto con tecnología probada pero sin financiación comprometida falla el criterio 5 — todo a gastos. Esta prueba de todo o nada es la frase más examinada de la NIC 38.' },
        table: { headers: ['Criterio', 'Qué pregunta'], rows: [['Viabilidad técnica', '¿Podemos construirlo realmente?'], ['Intención', '¿Planeamos terminarlo?'], ['Capacidad', '¿Podemos usarlo o venderlo?'], ['Beneficios futuros', '¿Existe un mercado?'], ['Recursos', '¿Tenemos financiación y capacidades para completarlo?'], ['Medición', '¿Podemos seguir el coste con fiabilidad?']] }
      },
      {
        heading: 'Caso práctico: el proyecto farmacéutico',
        paragraphs: [
          'Una farmacéutica gasta 2.000.000 $ en investigación en fase temprana (cribado de compuestos) y después 5.000.000 $ en desarrollar el candidato exitoso mediante ensayos. Los 2.000.000 $ de investigación se llevan a gastos de inmediato — sin debate. Para los 5.000.000 $ de desarrollo: la viabilidad técnica queda demostrada por los resultados de los ensayos, la empresa tiene intención de completarlo, puede vender el fármaco, existe un mercado, la financiación está asegurada y los costes se siguen por proyecto. Los seis cumplidos → capitalizar 5.000.000 $.',
          'Asientos: durante el desarrollo, Debe Activo de desarrollo (intangible) 5.000.000 $, Haber Efectivo/Cuentas a pagar 5.000.000 $. Cuando el fármaco se aprueba y está disponible para su uso, la amortización comienza a lo largo de su vida útil (digamos 10 años → 500.000 $/año). Si en algún momento falla un criterio — fracasan los ensayos — la capitalización se detiene y el activo se somete a prueba de deterioro.'
        ],
        journal: { transaction: 'Costes de desarrollo de 5.000.000 $ que cumplen los seis criterios de la NIC 38.', lines: [{ account: 'Activo de desarrollo (intangible)', dr: 5000000, cr: null }, { account: 'Efectivo / Cuentas a pagar', dr: null, cr: 5000000 }], narration: 'Capitalización de gastos de desarrollo que cualifican' },
        impact: { pl: 'Sin gasto inmediato — los 5 m $ quedan fuera de la cuenta de resultados hasta que empieza la amortización (entonces 500.000 $/año durante 10 años).', bs: 'Activo intangible +5.000.000 $; beneficio 5 m $ mayor que si se hubiera llevado a gastos.', cf: 'La salida de efectivo es operativa o de inversión según la política; la capitalización en sí no distorsiona la relación resultado-efectivo.' },
        callout: { type: 'key', text: 'Capitalizar 5 m $ de desarrollo en lugar de llevarlos a gastos aumenta el beneficio del ejercicio en 5 m $. Por eso los seis criterios son estrictos — y por eso los analistas ajustan la capitalización agresiva.' }
      },
      {
        heading: 'Amortización y vidas útiles indefinidas',
        paragraphs: [
          'Los intangibles de vida finita se amortizan a lo largo de su vida útil, reflejando el patrón de los beneficios — en línea recta por defecto. El valor residual es normalmente cero salvo que un tercero se haya comprometido a comprar el activo o exista un mercado activo. La vida útil se revisa anualmente; los cambios son cambios de estimación prospectivos.',
          'Los intangibles de vida indefinida — una marca sin límite previsible a los flujos de efectivo que genera, por ejemplo — NO se amortizan en absoluto. «Indefinida» no significa «infinita»: significa sin fin previsible. En su lugar, se someten a prueba de deterioro anualmente (y cuando existan indicios) según la NIC 36. La propia valoración de «indefinida» se revisa cada año — si un límite se vuelve previsible, la amortización comienza de forma prospectiva.'
        ],
        callout: { type: 'interview', text: '«¿Por qué no se amortiza una marca de vida indefinida?» Porque la amortización distribuye el coste a lo largo de una vida útil, y una vida indefinida no tiene periodo de distribución — cualquier cuota sería arbitraria. En su lugar, la prueba anual de deterioro garantiza que el valor en libros nunca supere el importe recuperable. Es disciplina mediante pruebas en lugar de mediante reparto.' }
      },
      {
        heading: 'Intangibles adquiridos y el vecino del fondo de comercio',
        paragraphs: [
          'En una combinación de negocios, la adquirente reconoce los intangibles identificables por separado del fondo de comercio a valor razonable — relaciones con clientes, tecnología, marcas. Esto importa porque el fondo de comercio no se amortiza y su deterioro no puede revertirse, mientras que los intangibles identificables normalmente sí se amortizan. Clasificar valor indebidamente en el fondo de comercio embellece los beneficios futuros (sin amortización) pero crea riesgo de deterioro.',
          'Los intangibles adquiridos por separado (una licencia comprada por 300.000 $) simplemente se reconocen al coste. La sutileza del reconocimiento solo existe para los activos generados internamente — por eso la NIC 38 dedica la mayor parte de su energía a la frontera investigación/desarrollo. En las entrevistas, conecta la NIC 38 con la NIC 36: el desarrollo capitalizado y las marcas de vida indefinida se someten a pruebas de deterioro, y los deterioros del fondo de comercio nunca se revierten (m14).'
        ],
        bullets: ['Adquiridos en una combinación de negocios: reconocer por separado del fondo de comercio a valor razonable.', 'Adquiridos por separado: reconocer al coste — directo.', 'Fondo de comercio y marcas generados internamente: nunca reconocidos.', 'Desarrollo capitalizado e intangibles de vida indefinida: se aplica la prueba de deterioro de la NIC 36.']
      }
    ],
    mistakes: [
      'Capitalizar gastos de investigación — la investigación siempre se lleva a gastos, sin excepciones.',
      'Capitalizar el desarrollo cuando solo se cumplen cinco de los seis criterios — se exigen los seis.',
      'Amortizar un intangible de vida indefinida — sin amortización; prueba anual de deterioro en su lugar.',
      'Reconocer marcas o fondo de comercio generados internamente — prohibido según la NIC 38.',
      'Iniciar la amortización de un activo de desarrollo antes de que esté disponible para su uso.',
      'Olvidar la prueba anual de deterioro para intangibles de vida indefinida y activos de desarrollo aún no en uso.'
    ],
    interviewQA: [
      { q: '¿Cuándo pueden capitalizarse los costes de desarrollo?', a: 'Solo cuando se cumplen los seis criterios de la NIC 38: viabilidad técnica, intención de completar, capacidad de usar o vender, probables beneficios económicos futuros, recursos adecuados para completar y medición fiable del coste. La investigación siempre se lleva a gastos. Si falla un solo criterio, todo el desembolso queda en la cuenta de resultados. La capitalización comienza solo desde el momento en que se cumplen los criterios — el gasto de la fase de investigación anterior nunca se capitaliza retroactivamente.' },
      { q: '¿Cómo se tratan de forma distinta los intangibles de vida indefinida?', a: 'No se amortizan, porque no hay vida útil sobre la que distribuir el coste — cualquier cuota sería arbitraria. En su lugar se someten a prueba de deterioro anualmente y cuando existan indicios según la NIC 36. La propia valoración de «indefinida» se revisa cada año; si una vida finita se vuelve previsible, la entidad pasa a amortizar de forma prospectiva como un cambio de estimación.' },
      { q: '¿Por qué preocupa a los analistas la capitalización agresiva del desarrollo?', a: 'Porque capitalizar en lugar de llevar a gastos infla directamente el beneficio y los activos actuales — cada euro capitalizado es un euro que no pasa por gastos. Los analistas comparan las ratios de capitalización entre competidores, comprueban si las revelaciones sobre los seis criterios son creíbles (sobre todo la viabilidad técnica y la existencia del mercado) y a veces ajustan llevando a gastos el desarrollo capitalizado para comparar la rentabilidad subyacente. Es uno de los canales más comunes de gestión del resultado en tecnología y farmacia.' }
    ],
    quiz: [
      { question: 'Los gastos de investigación según la NIC 38 son:', options: ['Capitalizados si el proyecto parece prometedor', 'Siempre llevados a gastos', 'Capitalizados y amortizados en 5 años', 'Diferidos hasta el lanzamiento del producto'], answer: 1, explanation: 'La investigación siempre se lleva a gastos — sin excepciones. Solo el desarrollo que cumpla los seis criterios puede capitalizarse.', difficulty: 'Foundation', topic: 'Research vs Development', skill: 'IFRS Fundamentals' },
      { question: 'Los costes de desarrollo pueden capitalizarse cuando:', options: ['Se cumplen tres cualesquiera de los seis criterios', 'Se cumplen los seis criterios de la NIC 38', 'La dirección tiene intención de completar el proyecto', 'El proyecto ha gastado más de 1.000.000 $'], answer: 1, explanation: 'Los seis criterios — viabilidad técnica, intención, capacidad, beneficios futuros, recursos, medición — deben cumplirse simultáneamente.', difficulty: 'Foundation', topic: 'Six Criteria', skill: 'IFRS Fundamentals' },
      { question: 'Un proyecto cumple cinco de los seis criterios pero carece de financiación comprometida. ¿Tratamiento?', options: ['Capitalizar 5/6 de los costes', 'Capitalizar y revelar el riesgo de financiación', 'Llevar a gastos todos los costes de desarrollo', 'Aplazar la decisión un año'], answer: 2, explanation: 'Los criterios son de todo o nada. Fallar la prueba de recursos significa no capitalizar — todo se lleva a gastos.', difficulty: 'Intermediate', topic: 'Six Criteria', skill: 'IFRS Fundamentals' },
      { question: 'Una marca de vida indefinida es:', options: ['No amortizada; sometida a prueba de deterioro anual', 'Amortizada en un máximo de 20 años', 'Amortizada a lo largo de su vida legal', 'Llevada a gastos de inmediato'], answer: 0, explanation: 'Los intangibles de vida indefinida eluden la amortización y se someten a pruebas anuales de deterioro de la NIC 36.', difficulty: 'Intermediate', topic: 'Indefinite Life', skill: 'IFRS Fundamentals' },
      { question: '¿Qué partida generada internamente NUNCA puede reconocerse como activo intangible?', options: ['Costes de desarrollo que cumplen los seis criterios', 'Una licencia de software adquirida', 'Una patente adquirida en una combinación de negocios', 'Una marca desarrollada por el propio marketing de la empresa'], answer: 3, explanation: 'Las marcas, el fondo de comercio, las cabeceras y las listas de clientes generados internamente nunca se reconocen — su coste no puede separarse del desarrollo del negocio.', difficulty: 'Intermediate', topic: 'Recognition', skill: 'IFRS Fundamentals' },
      { question: 'La amortización de un activo de desarrollo capitalizado comienza:', options: ['Cuando empieza el gasto de desarrollo', 'Cuando el activo está disponible para su uso', 'Cuando se cumple el primer criterio', 'Cuando el producto es rentable'], answer: 1, explanation: 'La amortización comienza con la disponibilidad para el uso — cuando el activo está en condiciones de operar según lo previsto.', difficulty: 'Intermediate', topic: 'Amortisation', skill: 'IFRS Fundamentals' },
      { question: '2 m $ de investigación + 5 m $ de desarrollo que cualifica en un proyecto farmacéutico. ¿Gasto en la cuenta de resultados este año?', options: ['2.000.000 $ (solo investigación)', '7.000.000 $', '0 $', '500.000 $'], answer: 0, explanation: 'La investigación de 2 m $ se lleva a gastos; el desarrollo que cualifica de 5 m $ se capitaliza (la amortización solo empieza cuando está disponible para su uso).', difficulty: 'Advanced', topic: 'Case', skill: 'IFRS Fundamentals' },
      { question: 'Si la valoración de «indefinida» de una marca cambia a una vida finita de 10 años, la entidad:', options: ['Reexpresa ejercicios anteriores con 10 años de amortización de puesta al día', 'Da de baja la marca de inmediato', 'Comienza a amortizar de forma prospectiva como cambio de estimación', 'La mantiene sin amortizar por comparabilidad'], answer: 2, explanation: 'El cambio es un cambio de estimación según la NIC 8: amortizar de forma prospectiva a lo largo de los 10 años restantes, sin reexpresión.', difficulty: 'Advanced', topic: 'Indefinite Life', skill: 'IFRS Fundamentals' },
      { question: 'El valor residual de un activo intangible se presume cero salvo que:', options: ['La dirección estime un valor de desecho', 'Sea un activo de software', 'El activo sea de vida indefinida', 'Un tercero se comprometa a comprarlo o exista un mercado activo'], answer: 3, explanation: 'La NIC 38 establece una presunción refutable de valor residual cero, solo superada por un compromiso de compra o un mercado activo.', difficulty: 'Advanced', topic: 'Amortisation', skill: 'IFRS Fundamentals' }
    ]
  },
  {
    id: 'm14', level: 3, levelTitle: 'Operating Accounting', title: 'NIC 36 — Deterioro del valor de los activos',
    standard: 'IAS 36', tagline: 'Cuando los activos valen menos de lo que dicen los libros: medir, distribuir y (a veces) revertir el deterioro.',
    description: 'La NIC 36 garantiza que los activos no se valoren por encima de su importe recuperable. Aprenderás el valor en uso frente al valor razonable menos los costes de enajenación, las unidades generadoras de efectivo, las reglas de distribución del fondo de comercio — incluida la ley de hierro de que los deterioros del fondo de comercio nunca se revierten — mediante ejercicios de cálculo.',
    minutes: 20, skills: ['IFRS Fundamentals'],
    sections: [
      {
        heading: 'La prueba central: valor en libros frente a importe recuperable',
        paragraphs: [
          'En cada fecha de cierre la entidad evalúa si existen indicios de deterioro — caídas del valor de mercado, cambios tecnológicos o económicos adversos, subida de los tipos de interés, daños físicos o un desempeño peor del esperado. Si existen indicios (y siempre anualmente para el fondo de comercio y los intangibles de vida indefinida), se estima el importe recuperable del activo. Si el valor en libros supera el importe recuperable, la diferencia es una pérdida por deterioro reconocida de inmediato en la cuenta de resultados.',
          'El importe recuperable es el MAYOR entre el valor en uso y el valor razonable menos los costes de enajenación. La lógica: un propietario racional seguiría usando el activo (valor en uso) o lo vendería (valor razonable menos costes) — lo que rinda más. Tomar el mayor de los dos no es optimismo; refleja las opciones reales disponibles.'
        ],
        callout: { type: 'key', text: 'Importe recuperable = MAYOR entre (a) el valor en uso y (b) el valor razonable menos los costes de enajenación. Pérdida por deterioro = valor en libros − importe recuperable (cuando es positiva), reconocida en la cuenta de resultados.' }
      },
      {
        heading: 'Valor en uso frente a valor razonable menos costes de enajenación',
        paragraphs: [
          'El valor en uso es específico de la entidad: el valor actual de los flujos de efectivo futuros por seguir usando el activo, descontado a un tipo antes de impuestos que refleje las valoraciones actuales del mercado sobre el valor temporal y los riesgos del activo. Las proyecciones usan las hipótesis razonables de la dirección (máximo 5 años de presupuestos salvo justificación) y después una tasa de crecimiento estable o decreciente para la extrapolación. Los beneficios de reestructuraciones se excluyen salvo que la entidad ya esté comprometida.',
          'El valor razonable menos los costes de enajenación se basa en el mercado: el precio en una transacción ordenada entre participantes del mercado (NIIF 13), menos los costes de enajenación como honorarios jurídicos y costes de desmontaje. Si existe una cotización en un mercado activo, domina; en caso contrario se aplican técnicas de valoración. En la práctica, se comprueban ambos y se toma el mayor — trabajado a continuación.'
        ],
        callout: { type: 'example', text: 'Máquina: valor en libros 500.000 $. Valor en uso 420.000 $; valor razonable menos costes de enajenación 450.000 $. Importe recuperable = 450.000 $ (el mayor). Pérdida por deterioro = 500.000 $ − 450.000 $ = 50.000 $: Debe Pérdidas por deterioro 50.000 $, Haber Deterioro acumulado 50.000 $.' }
      },
      {
        heading: 'Ejercicio de cálculo: deterioro completo paso a paso',
        paragraphs: [
          'Una línea de producción: coste 1.200.000 $, amortización acumulada 400.000 $ → valor en libros 800.000 $. Existen indicios (nueva tecnología). El valor en uso se calcula en 620.000 $; el valor razonable menos costes de enajenación en 580.000 $. Importe recuperable = 620.000 $ (el mayor). Pérdida por deterioro = 800.000 $ − 620.000 $ = 180.000 $.',
          'Tras el deterioro el valor en libros es 620.000 $, y la amortización futura se basa en el nuevo valor en libros a lo largo de la vida útil restante — un cambio de estimación prospectivo. Si a la línea le quedaran 4 años de vida, la nueva amortización anual = 620.000 $ ÷ 4 = 155.000 $ (ignorando el residual). El deterioro no solo golpea el beneficio una vez; reinicia la base de amortización en adelante.'
        ],
        journal: { transaction: 'Deterioro de la línea de producción: valor en libros 800.000 $, importe recuperable 620.000 $.', lines: [{ account: 'Pérdidas por deterioro', dr: 180000, cr: null }, { account: 'Deterioro acumulado — Línea de producción', dr: null, cr: 180000 }], narration: 'Pérdida por deterioro: el valor en libros supera el importe recuperable' },
        impact: { pl: 'Pérdida por deterioro de 180.000 $ reconocida de inmediato; la amortización futura cae a 155.000 $/año.', bs: 'Línea de producción valorada a 620.000 $; patrimonio neto −180.000 $.', cf: 'Sin efecto en el efectivo — un deterioro no monetario.' }
      },
      {
        heading: 'Unidades generadoras de efectivo y fondo de comercio',
        paragraphs: [
          'Muchos activos no generan flujos de efectivo independientes — una máquina en una fábrica no vale nada sola. La NIC 36 los agrupa en unidades generadoras de efectivo (UGE): el grupo identificable más pequeño de activos que genera entradas de efectivo en gran medida independientes. El fondo de comercio, que nunca genera efectivo por sí solo, se distribuye a las UGE (o grupos) que se espera se beneficien de las sinergias, y se somete a prueba anualmente.',
          'El orden de distribución del deterioro dentro de una UGE es estricto: PRIMERO reducir el fondo de comercio a cero, DESPUÉS reducir los demás activos a prorrata según el valor en libros (pero ningún activo por debajo de su importe recuperable individual). El fondo de comercio absorbe el golpe primero porque es el activo más subjetivo y menos separable — la prima pagada sobre el valor identificable.'
        ],
        callout: { type: 'warning', text: 'LOS DETERIOROS DEL FONDO DE COMERCIO NUNCA SE REVIERTEN. Esta es la ley de hierro de la NIC 36. La razón: un aumento posterior del importe recuperable probablemente sea fondo de comercio generado internamente, cuyo reconocimiento prohíbe la NIC 38. Los deterioros de otros activos pueden revertirse — los del fondo de comercio no.' },
        table: { headers: ['Valor en libros de la UGE', 'Importe recuperable', 'Deterioro'], rows: [['Fondo de comercio 200.000 $ + activos 800.000 $ = 1.000.000 $', '750.000 $', '250.000 $: fondo de comercio → 0 $, activos → 750.000 $']] }
      },
      {
        heading: 'Reversiones: todo excepto el fondo de comercio',
        paragraphs: [
          'Para activos distintos del fondo de comercio, si el importe recuperable aumenta después, el deterioro se revierte — pero con el límite de que el valor en libros nunca supere el que habría tenido sin el deterioro (la senda original de amortización). La reversión se reconoce en la cuenta de resultados (o en otro resultado global si el activo se valora por revalorización).',
          'Ejemplo: la línea de producción deteriorada hasta 620.000 $ con 4 años restantes. Un año después (amortización 155.000 $ → valor 465.000 $), el importe recuperable se reevalúa en 700.000 $. Sin deterioro el valor en libros habría sido 800.000 $ − 200.000 $ = 600.000 $ (amortización original de 200.000 $/año × 1 año… ajustado). La reversión tiene como techo el valor en libros sin deterioro. El fondo de comercio, mientras tanto, queda deteriorado para siempre — memoriza esta asimetría, porque examinadores y entrevistadores la ponen a prueba constantemente.'
        ],
        callout: { type: 'interview', text: '«¿Por qué no pueden revertirse los deterioros del fondo de comercio?» Porque cualquier recuperación de valor tras un deterioro del fondo de comercio es indistinguible del fondo de comercio generado internamente — cuyo reconocimiento prohíbe la NIC 38. Revertir introduciría de contrabando fondo de comercio autogenerado en el balance. La norma prefiere un deterioro permanente a un activo ficticio.' }
      }
    ],
    mistakes: [
      'Usar el MENOR entre el valor en uso y el valor razonable menos costes de enajenación — el importe recuperable es el MAYOR de los dos.',
      'Revertir un deterioro del fondo de comercio cuando mejoran las condiciones — nunca permitido según la NIC 36.',
      'Someter a prueba una sola máquina cuando no tiene flujos de efectivo independientes — se somete la UGE.',
      'Distribuir el deterioro de la UGE a prorrata antes de llevar el fondo de comercio a cero — el fondo de comercio absorbe primero.',
      'Revertir un deterioro por encima del valor en libros sin deterioro — el techo es la senda original de amortización.',
      'Incluir beneficios de reestructuraciones no comprometidas en los flujos del valor en uso.'
    ],
    interviewQA: [
      { q: '¿Cómo se calcula una pérdida por deterioro? Dame los pasos.', a: 'Primero comprobar los indicios (o someter a prueba anualmente el fondo de comercio y los intangibles de vida indefinida). Después estimar el importe recuperable — el mayor entre el valor en uso (flujos de efectivo futuros descontados por el uso continuado) y el valor razonable menos los costes de enajenación. Comparar con el valor en libros: si el valor en libros supera el recuperable, la diferencia es la pérdida por deterioro, reconocida de inmediato en la cuenta de resultados. Después, amortizar el nuevo valor en libros a lo largo de la vida restante de forma prospectiva. Para una UGE, distribuir la pérdida primero al fondo de comercio y después a prorrata a los demás activos.' },
      { q: 'Una UGE tiene fondo de comercio de 200.000 $ y otros activos de 800.000 $; el importe recuperable es 750.000 $. Distribuye el deterioro.', a: 'Valor total en libros 1.000.000 $ frente a recuperable 750.000 $ → deterioro 250.000 $. El fondo de comercio se reduce primero: 200.000 $ hasta cero, absorbiendo 200.000 $. Los 50.000 $ restantes se distribuyen a prorrata entre los demás activos, dejándolos en 750.000 $ en total. Ningún activo individual puede reducirse por debajo de su propio importe recuperable. Y el deterioro del fondo de comercio de 200.000 $ nunca podrá revertirse.' },
      { q: '¿Cuándo puede revertirse una pérdida por deterioro?', a: 'Para todos los activos excepto el fondo de comercio, cuando el importe recuperable aumenta por cambios en las estimaciones — la reversión se reconoce en la cuenta de resultados, con el límite del valor en libros que habría correspondido sin el deterioro (la senda original de amortización). Los deterioros del fondo de comercio nunca se revierten, porque la recuperación representaría fondo de comercio generado internamente, cuyo reconocimiento prohíbe la NIC 38.' }
    ],
    quiz: [
      { question: 'El importe recuperable se define como:', options: ['El menor entre el valor en uso y el valor razonable menos los costes de enajenación', 'Solo el valor en uso', 'El coste original menos la amortización acumulada', 'El mayor entre el valor en uso y el valor razonable menos los costes de enajenación'], answer: 3, explanation: 'La NIC 36 toma el mayor — el propietario elegiría la mejor opción entre el uso continuado o la venta.', difficulty: 'Foundation', topic: 'Recoverable Amount', skill: 'IFRS Fundamentals' },
      { question: 'Valor en libros 500.000 $; valor en uso 420.000 $; VR menos costes 450.000 $. ¿Pérdida por deterioro?', options: ['50.000 $', '80.000 $', '30.000 $', '0 $'], answer: 0, explanation: 'Recuperable = mayor entre 420.000 $ y 450.000 $ = 450.000 $. Pérdida = 500.000 $ − 450.000 $ = 50.000 $.', difficulty: 'Intermediate', topic: 'Calculation', skill: 'IFRS Fundamentals' },
      { question: 'Línea de producción: valor 800.000 $, recuperable 620.000 $. El asiento es:', options: ['Debe Deterioro acumulado 180.000 $; Haber Pérdidas por deterioro 180.000 $', 'Debe Pérdidas por deterioro 180.000 $; Haber Deterioro acumulado 180.000 $', 'Debe Amortización 180.000 $; Haber Línea de producción 180.000 $', 'Sin asiento hasta que se venda la línea'], answer: 1, explanation: 'Pérdida = 800.000 $ − 620.000 $ = 180.000 $, reconocida de inmediato en la cuenta de resultados.', difficulty: 'Foundation', topic: 'Journal Entries', skill: 'IFRS Fundamentals' },
      { question: 'Tras el deterioro de 180.000 $ con 4 años de vida restantes, la nueva amortización anual es:', options: ['200.000 $', '45.000 $', '155.000 $', '180.000 $'], answer: 2, explanation: '620.000 $ ÷ 4 = 155.000 $ al año, aplicado de forma prospectiva sobre el nuevo valor en libros.', difficulty: 'Advanced', topic: 'Calculation', skill: 'IFRS Fundamentals' },
      { question: 'Una máquina no puede generar flujos de efectivo de forma independiente. Debe someterse a prueba de deterioro:', options: ['Como parte de su unidad generadora de efectivo', 'Por sí sola usando el coste de reposición', 'Solo cuando se venda', 'Nunca — solo se someten los activos independientes'], answer: 0, explanation: 'Los activos sin flujos de efectivo independientes se agrupan en la UGE más pequeña que genere entradas en gran medida independientes.', difficulty: 'Intermediate', topic: 'CGUs', skill: 'IFRS Fundamentals' },
      { question: 'Un deterioro de la UGE de 250.000 $ con fondo de comercio de 200.000 $ y activos de 800.000 $ se distribuye:', options: ['250.000 $ a prorrata entre todos los activos incluido el fondo de comercio', '250.000 $ solo al fondo de comercio', 'Íntegramente al activo individual más grande', '200.000 $ al fondo de comercio (hasta cero), 50.000 $ a prorrata a los demás activos'], answer: 3, explanation: 'El fondo de comercio absorbe el deterioro primero, hasta cero; solo el resto va a prorrata a los demás activos.', difficulty: 'Advanced', topic: 'CGUs', skill: 'IFRS Fundamentals' },
      { question: 'Una pérdida por deterioro del fondo de comercio:', options: ['Puede revertirse cuando se recupera el importe recuperable', 'Nunca puede revertirse', 'Se revierte automáticamente tras 5 años', 'Se abona a otro resultado global en la reversión'], answer: 1, explanation: 'La NIC 36 prohíbe revertir los deterioros del fondo de comercio — la recuperación sería fondo de comercio generado internamente.', difficulty: 'Foundation', topic: 'Goodwill', skill: 'IFRS Fundamentals' },
      { question: 'El valor en uso se basa en:', options: ['El precio de venta actual en el mercado', 'El coste histórico indexado por la inflación', 'Los flujos de efectivo futuros descontados por seguir usando el activo', 'El coste de reposición nuevo'], answer: 2, explanation: 'El valor en uso es específico de la entidad: valor actual de los flujos de efectivo por el uso continuado, descontado a un tipo antes de impuestos adecuado.', difficulty: 'Intermediate', topic: 'Value in Use', skill: 'IFRS Fundamentals' },
      { question: 'La reversión de un deterioro para un activo distinto del fondo de comercio tiene como techo:', options: ['El coste histórico original', 'El valor en libros sin el deterioro original (senda original de amortización)', 'El valor razonable en la fecha de la reversión', 'No hay techo'], answer: 1, explanation: 'Las reversiones restauran pero nunca superan lo que habría sido el valor en libros — el activo no puede revaluarse al alza mediante una reversión.', difficulty: 'Advanced', topic: 'Reversals', skill: 'IFRS Fundamentals' }
    ]
  }
];
