export default [
  {
    id: 'm22', level: 6, levelTitle: 'Group Accounting', title: 'Fundamentos de la consolidación',
    standard: 'IFRS 10', tagline: 'Un grupo es una entidad económica — aunque los abogados digan que son veinte.',
    description: 'La NIIF 10 exige que una matriz que controla filiales presente estados financieros consolidados. Este módulo construye la mentalidad de consolidación: qué significa el control a alto nivel, cómo funciona la participación no dominante, y las tres eliminaciones que toda consolidación debe acertar — saldos intragrupo, ventas intragrupo, y beneficio no realizado en existencias.',
    minutes: 20, skills: ['Consolidation'],
    sections: [
      {
        heading: 'Por qué los grupos consolidan',
        paragraphs: [
          'Legalmente, una matriz y sus filiales son empresas separadas. Económicamente, son un solo negocio bajo control común — e inversores, prestamistas y reguladores quieren ver esa realidad económica. La NIIF 10 exige, por tanto, que una matriz presente estados financieros consolidados: los activos, pasivos, patrimonio neto, ingresos, gastos y flujos de efectivo de la matriz y todas sus filiales presentados como si pertenecieran a una sola entidad.',
          'La consolidación es también un mecanismo antiabuso. Sin ella, un grupo podría ocultar deuda en una filial, trasladar beneficios entre entidades con precios de transferencia, o hacer que la matriz parezca ligera en activos mientras el grupo está muy apalancado. Los estados consolidados eliminan la fontanería interna y muestran solo las operaciones del grupo con el mundo exterior.'
        ],
        callout: { type: 'key', text: 'La consolidación presenta al grupo como una sola entidad económica. Todo lo que el grupo hace consigo mismo se elimina; solo permanecen las transacciones con terceros.' }
      },
      {
        heading: 'Matriz, filial y control — el vocabulario',
        paragraphs: [
          'Una matriz es una entidad que controla una o más entidades. Una filial es una entidad controlada por otra entidad. El activador de la consolidación es el control, no el porcentaje poseído: una empresa participada al 51 % se consolida igual que una al 100 %, mientras que una participación del 40 % sin control no se consolida (puede ser una asociada o una simple inversión).',
          'La NIIF 10 define el control a través de tres elementos acumulativos: poder sobre la participada, exposición (o derechos) a rendimientos variables por su implicación en ella, y la capacidad de usar ese poder para afectar al importe de dichos rendimientos. Los tres deben estar presentes. El módulo m23 desmonta cada elemento con ejemplos reales; por ahora, recordar que el control trata del fondo — quién manda realmente — no solo del conteo de certificados de acciones.'
        ],
        bullets: ['Matriz: la entidad que controla.', 'Filial: la entidad que es controlada.', 'Activador de la consolidación: el control, no la propiedad del 100 %.', 'Control en resumen: poder + rendimientos variables + la capacidad de vincular ambos.']
      },
      {
        heading: 'Participación no dominante (PND)',
        paragraphs: [
          'Cuando la matriz posee menos del 100 % de una filial — digamos el 80 % — el 20 % restante pertenece a inversores externos. Esa porción es la participación no dominante (PND), antes llamada interés minoritario. La consolidación incorpora el 100 % de los activos, pasivos, ingresos y gastos de la filial, y después muestra por separado la parte de la PND para que los lectores vean qué pertenece a los accionistas de la matriz y qué a otros.',
          'En el balance consolidado, la PND se presenta dentro del patrimonio neto, por separado del patrimonio atribuible a los propietarios de la matriz. No es un pasivo: los tenedores de la PND son propietarios, no acreedores. En la cuenta de resultados consolidada, se incluye el resultado íntegro de la filial y después se reparte: resultado atribuible a los propietarios de la matriz, y resultado atribuible a la PND. En la adquisición, la NIIF 3 permite al grupo valorar la PND bien a valor razonable (método del fondo de comercio completo) o bien por su parte proporcional de los activos netos identificables de la filial (método del fondo de comercio parcial).'
        ],
        callout: { type: 'warning', text: 'La PND está dentro del patrimonio neto, no en los pasivos. Clasificarla como deuda sobrevalora el apalancamiento y engaña a cada acreedor que lea el balance.' },
        journal: {
          transaction: 'Reconocer la PND y el fondo de comercio: la matriz paga $400,000 en efectivo por el 80 % de la filial; los activos netos identificables de la filial tienen un valor razonable de $450,000',
          lines: [
            { account: 'Activos netos identificables (filial, a valor razonable)', dr: 450000, cr: null },
            { account: 'Fondo de comercio', dr: 40000, cr: null },
            { account: 'Inversión en filial (libros de la matriz)', dr: null, cr: 400000 },
            { account: 'Participación no dominante (20% x $450,000)', dr: null, cr: 90000 }
          ],
          narration: 'Fondo de comercio = $400,000 de contraprestación − 80% x $450,000 = $40,000. La inversión de una línea de la matriz se sustituye por los activos netos íntegros de la filial, el fondo de comercio y la parte de la PND, usando el método del fondo de comercio parcial.'
        },
        impact: { pl: 'Sin efecto inmediato en resultados el día de la adquisición (los costes relacionados con la adquisición se llevan a gastos por separado).', bs: 'Fondo de comercio de $40,000 reconocido como activo; PND de $90,000 presentada dentro del patrimonio neto.', cf: 'Los $400,000 en efectivo pagados aparecen en las actividades de inversión.' }
      },
      {
        heading: 'Eliminaciones I: saldos y transacciones intragrupo',
        paragraphs: [
          'Si el grupo es una entidad económica, no puede deberse dinero a sí mismo ni venderse a sí mismo. Por eso cada saldo y transacción intragrupo se elimina en su totalidad. La cuenta a cobrar de la matriz a la filial se cancela contra la cuenta a pagar de la filial a la matriz. Los ingresos por dividendos de la matriz de la filial se cancelan contra la distribución de dividendos de la filial. Las ventas intragrupo y las compras intragrupo correspondientes se cancelan para que los ingresos consolidados reflejen solo las ventas a clientes externos.',
          'La mecánica es simple pero la disciplina lo es todo: las eliminaciones deben ser completas y simétricas. Eliminar la cuenta a cobrar pero olvidar la cuenta a pagar, y el balance consolidado no cuadrará. Eliminar la venta pero olvidar la compra, y el margen bruto se distorsiona. En la práctica, los grupos ejecutan un proceso de conciliación intragrupo antes de la consolidación (ver m25) precisamente porque estas eliminaciones solo funcionan cuando ambas partes coinciden en los importes.'
        ],
        bullets: ['Cuenta a cobrar frente a cuenta a pagar: ambas eliminadas, sin efecto en resultados.', 'Venta intragrupo frente a compra: ingresos ordinarios y coste de ventas ambos eliminados.', 'Dividendos intragrupo: los ingresos por dividendos de la matriz eliminados contra la distribución de la filial.', 'Préstamos intragrupo: activo de préstamo frente a pasivo de préstamo eliminados, con los intereses devengados también.']
      },
      {
        heading: 'Eliminaciones II: beneficio no realizado en existencias',
        paragraphs: [
          'La eliminación más sutil concierne al beneficio que el grupo aún no ha ganado realmente. Supongamos que la matriz vende mercancías que costaron $40,000 a la filial por $50,000, y la filial aún las mantiene en existencias al cierre. Desde la perspectiva del grupo no ha pasado nada: las mercancías simplemente se movieron de un almacén a otro, pero los libros de la matriz muestran un beneficio de $10,000. Ese beneficio no está realizado — solo se vuelve real cuando la filial vende las mercancías a un cliente externo.',
          'La consolidación, por tanto, elimina la venta intragrupo completa y quita el margen de $10,000 de las existencias, devolviéndolas a su coste original ($40,000). Nótese la palabra completa: bajo el enfoque de eliminación total, todo el beneficio no realizado se elimina del resultado del grupo con independencia del porcentaje de la PND. (Cómo se atribuye el beneficio no realizado entre matriz y PND en ventas ascendentes frente a descendentes es un refinamiento más allá de este módulo.)'
        ],
        callout: { type: 'example', text: 'La matriz vende a la filial por $50,000 (coste $40,000); mercancías sin vender al cierre. Eliminación: Debe Ingresos ordinarios $50,000, Haber Coste de ventas $40,000, Haber Existencias $10,000. Los ingresos del grupo caen $50,000, las existencias del grupo caen a su coste real $40,000, el resultado del grupo cae $10,000.' },
        journal: {
          transaction: 'Eliminar el beneficio no realizado: venta intragrupo de $50,000 (coste $40,000), mercancías aún en las existencias de la filial',
          lines: [
            { account: 'Ingresos ordinarios', dr: 50000, cr: null },
            { account: 'Coste de ventas', dr: null, cr: 40000 },
            { account: 'Existencias', dr: null, cr: 10000 }
          ],
          narration: 'Eliminar la venta intragrupo en su totalidad y quitar el margen no realizado de $10,000 de las existencias de la filial, dejándolas al coste original del grupo.'
        },
        impact: { pl: 'Los ingresos ordinarios y el coste de ventas del grupo caen; el margen bruto del grupo cae por el margen no realizado de $10,000.', bs: 'Las existencias se valoran a su coste original de $40,000; no queda cuenta a cobrar ni a pagar intragrupo.', cf: 'Sin efecto en efectivo — es un ajuste solo de consolidación.' }
      }
    ],
    mistakes: [
      'Consolidar solo filiales participadas al 100 %: una empresa participada al 51 % está controlada y debe consolidarse, mostrando la PND para el resto.',
      'Eliminar la cuenta a cobrar intragrupo pero olvidar la cuenta a pagar correspondiente — el balance no cuadrará.',
      'Eliminar la venta intragrupo pero no la compra: los ingresos caen mientras el coste de ventas permanece, distorsionando el margen bruto.',
      'Dejar el beneficio no realizado en existencias, lo que sobrevalora tanto el resultado como los activos del grupo.',
      'Presentar la PND como un pasivo en lugar de dentro del patrimonio neto, lo que sobrevalora el apalancamiento del grupo.',
      'Olvidar eliminar los dividendos intragrupo: los ingresos por dividendos de la matriz y la distribución de la filial deben desaparecer ambos.'
    ],
    interviewQA: [
      { q: '¿Por qué se eliminan las transacciones intragrupo en la consolidación?', a: 'Porque los estados consolidados presentan al grupo como una sola entidad económica, y una entidad no puede operar consigo misma. Dejar las ventas intragrupo duplicaría ingresos y beneficios; dejar los saldos intragrupo inflaría activos y pasivos. Las eliminaciones aseguran que solo permanezcan las transacciones con el mundo exterior. La que más comúnmente se olvida es el beneficio no realizado en existencias: las mercancías trasladadas entre empresas del grupo con margen deben devolverse a su coste original hasta venderse externamente.' },
      { q: '¿Qué es la participación no dominante y dónde aparece?', a: 'La PND es la parte del patrimonio de una filial no poseída por la matriz — por ejemplo el 20 % cuando la matriz posee el 80 %. La consolidación incluye el 100 % de los activos, pasivos, ingresos y gastos de la filial, y después muestra por separado la parte de la PND: dentro del patrimonio neto en el balance (nunca como pasivo), y como línea separada de atribución del resultado en la cuenta de resultados. En la adquisición, la NIIF 3 permite valorar la PND a valor razonable o por su parte proporcional de los activos netos identificables.' },
      { q: 'La matriz vende mercancías a su filial con beneficio y las mercancías están sin vender al cierre. ¿Cuál es el ajuste de consolidación?', a: 'Eliminar la venta intragrupo completa — debe a ingresos ordinarios por el precio de venta — y quitar el margen no realizado de las existencias para que se valoren al coste original para el grupo: haber a coste de ventas por el coste original y haber a existencias por el margen. El resultado del grupo cae por el importe no realizado porque, económicamente, el grupo solo ha movido mercancías entre sus propios almacenes. En el periodo siguiente, cuando la filial venda externamente, se reconoce el beneficio.' }
    ],
    quiz: [
      { question: '¿Qué son los estados financieros consolidados?', options: ['Solo los estados financieros separados de la matriz', 'Una simple suma de los balances de comprobación de todas las empresas del grupo sin ajustes', 'Los estados financieros de un grupo, que presentan a la matriz y sus filiales como una sola entidad económica', 'Los estados financieros de la filial convertidos a la moneda de la matriz'], answer: 2, explanation: 'La consolidación no es una simple suma: los saldos y transacciones intragrupo se eliminan para presentar al grupo como una entidad económica, como exige la NIIF 10.', difficulty: 'Foundation', topic: 'Consolidation Basics', skill: 'Consolidation' },
      { question: '¿Cuál de las siguientes define mejor una filial?', options: ['Cualquier empresa en la que otra empresa posee acciones', 'Una entidad controlada por otra entidad (su matriz)', 'Una entidad que opera en un país extranjero', 'Una empresa adquirida en los últimos doce meses'], answer: 1, explanation: 'El control es el criterio definitorio — no el tamaño de la participación, la ubicación ni la fecha de adquisición.', difficulty: 'Foundation', topic: 'Consolidation Basics', skill: 'Consolidation' },
      { question: 'La matriz posee el 70 % de la filial. La filial informa un resultado de $100,000 para el año. ¿Cuánto del resultado de la filial se atribuye a la participación no dominante?', options: ['$0 — todo el resultado pertenece a la matriz', '$70,000', '$100,000', '$30,000'], answer: 3, explanation: 'La PND posee el 30 %, por lo que el 30 % x $100,000 = $30,000 se atribuye a la PND y se muestra como línea separada en la cuenta de resultados consolidada.', difficulty: 'Intermediate', topic: 'NCI', skill: 'Consolidation' },
      { question: 'La matriz vendió mercancías que costaron $40,000 a su filial por $50,000. Al cierre las mercancías siguen en las existencias de la filial. ¿Qué eliminación es correcta?', options: ['Debe Ingresos ordinarios $50,000 / Haber Coste de ventas $40,000 / Haber Existencias $10,000', 'Debe Existencias $10,000 / Haber Coste de ventas $10,000', 'Debe Ingresos ordinarios $50,000 / Haber Existencias $50,000', 'Sin eliminación — la venta fue a precio de mercado'], answer: 0, explanation: 'La venta intragrupo completa ($50,000) se elimina y el margen no realizado de $10,000 se quita de las existencias, dejándolas a su coste original ($40,000). El precio de mercado es irrelevante dentro del grupo.', difficulty: 'Intermediate', topic: 'Unrealized Profit', skill: 'Consolidation' },
      { question: 'La empresa A (matriz) muestra una cuenta a cobrar de $20,000 de la empresa B (filial), y B muestra una cuenta a pagar de $20,000 a A. ¿Cuál es el efecto de eliminarlas en la consolidación?', options: ['El resultado del grupo cae $20,000', 'Los activos y pasivos del grupo caen $20,000; el resultado del grupo no cambia', 'El patrimonio neto del grupo cae $20,000', 'No hay efecto en ningún total consolidado'], answer: 1, explanation: 'La cuenta a cobrar y la cuenta a pagar se cancelan: activos bajan $20,000, pasivos bajan $20,000. No hay efecto en resultados porque no hubo margen involucrado.', difficulty: 'Intermediate', topic: 'Eliminations', skill: 'Consolidation' },
      { question: 'Bajo la NIIF 3, la participación no dominante en la adquisición puede valorarse a:', options: ['Siempre a valor razonable — no se permite elección', 'El valor contable del patrimonio de la filial', 'Valor razonable, o la parte proporcional de la PND de los activos netos identificables', 'Cero, porque la PND no se reconoce en la adquisición'], answer: 2, explanation: 'La NIIF 3 ofrece una elección para cada adquisición: valor razonable (método del fondo de comercio completo) o la parte proporcional de los activos netos identificables (método del fondo de comercio parcial).', difficulty: 'Advanced', topic: 'NCI', skill: 'Consolidation' },
      { question: 'El grupo olvida eliminar $10,000 de beneficio no realizado en las existencias al cierre de una filial. ¿Qué está distorsionado?', options: ['El resultado del grupo está infravalorado en $10,000', 'Solo se ven afectados los estados financieros separados de la filial', 'El efectivo del grupo está sobrevalorado en $10,000', 'El resultado y las existencias del grupo están sobrevalorados en $10,000'], answer: 3, explanation: 'El margen fantasma infla el resultado consolidado (ingresos sin venta real) e infla las existencias por encima de su coste real para el grupo. El efectivo no se ve afectado.', difficulty: 'Intermediate', topic: 'Unrealized Profit', skill: 'Consolidation' },
      { question: 'La matriz vende mercancías a la filial (una venta descendente) con $10,000 de beneficio no realizado aún en las existencias de la filial al cierre. Bajo el enfoque de eliminación total:', options: ['Los $10,000 completos se eliminan del resultado del grupo', 'Solo se elimina la parte proporcional de la matriz de los $10,000', 'No se elimina nada para ventas descendentes', 'Los $10,000 se cargan contra la PND'], answer: 0, explanation: 'La eliminación total quita todo el beneficio no realizado del resultado y de las existencias del grupo. La atribución del ajuste entre matriz y PND en casos ascendentes frente a descendentes es un refinamiento más allá de este módulo.', difficulty: 'Advanced', topic: 'Unrealized Profit', skill: 'Consolidation' },
      { question: '¿Dónde se presenta la participación no dominante en los estados financieros consolidados?', options: ['Como un pasivo no corriente', 'Como una provisión', 'Dentro del patrimonio neto, por separado del patrimonio atribuible a los propietarios de la matriz', 'Neteada contra el fondo de comercio'], answer: 2, explanation: 'Los tenedores de la PND son propietarios, no acreedores, por lo que la PND está dentro del patrimonio neto — mostrada en su propia línea para que los lectores la distingan del patrimonio de los accionistas de la matriz.', difficulty: 'Foundation', topic: 'NCI', skill: 'Consolidation' }
    ]
  },
  {
    id: 'm23', level: 6, levelTitle: 'Group Accounting', title: 'NIIF 10 — Control',
    standard: 'IFRS 10', tagline: 'El control no es un porcentaje. Es poder, rendimientos y el vínculo entre ellos.',
    description: 'Este módulo disecciona la definición de control de la NIIF 10: poder sobre la participada, exposición a rendimientos variables, y la capacidad de usar el poder para afectar a dichos rendimientos. Se trabajará la mayoría de voto, el control de hecho, los derechos de voto potenciales, las situaciones principal-frente a-agente, y las entidades estructuradas — los casos en los que el porcentaje de acciones miente.',
    minutes: 18, skills: ['Consolidation'],
    sections: [
      {
        heading: 'Los tres elementos del control',
        paragraphs: [
          'La NIIF 10 dice que un inversor controla una participada si y solo si tiene los tres siguientes: (1) poder sobre la participada — derechos existentes que dan la capacidad actual de dirigir las actividades relevantes, es decir, las actividades que más afectan a los rendimientos; (2) exposición, o derechos, a rendimientos variables por su implicación — rendimientos que varían con el rendimiento de la participada, como dividendos, ahorros de costes, sinergias, o intereses residuales en la liquidación; y (3) la capacidad de usar su poder para afectar al importe de dichos rendimientos — el vínculo entre poder y rendimientos.',
          'Los tres son acumulativos. Poder sin rendimientos (un gerente contratado pagado con una comisión fija sin potencial de mejora) no es control. Rendimientos sin poder (un accionista pasivo del 10 %) no es control. Y poder más rendimientos sin el vínculo — por ejemplo un gestor de fondos que debe actuar estrictamente en interés de los inversores y puede ser destituido a voluntad — tampoco es control. La evaluación es continua: el control se reevalúa siempre que cambian los hechos y circunstancias.'
        ],
        callout: { type: 'key', text: 'Control = poder + exposición a rendimientos variables + la capacidad de usar el poder para afectar a los rendimientos. Si falta uno de los tres, no hay control.' }
      },
      {
        heading: 'Poder I: mayoría de derechos de voto',
        paragraphs: [
          'El caso directo: poseer más de la mitad de los derechos de voto suele dar poder, porque permite al inversor nombrar al consejo y dirigir la estrategia, los presupuestos y las transacciones importantes — las actividades relevantes de una empresa operativa típica. Pero la NIIF 10 insiste en mirar más allá del porcentaje titular en ambas direcciones: a veces menos de la mitad basta (control de hecho), y a veces más de la mitad no basta.',
          'Una mayoría puede no dar poder cuando otro posee derechos de voto potenciales sustantivos que cambiarían el control, cuando los derechos de voto están restringidos por contrato o regulación, o cuando el inversor actúa como agente de otros en lugar de por sí mismo. La pregunta es siempre: ¿quién puede actualmente dirigir las actividades que importan?'
        ],
        bullets: ['>50 % de los derechos de voto: el poder se presume, después se verifica.', 'Actividades relevantes: las que más afectan a los rendimientos — estrategia, presupuestos, nombramientos clave, transacciones importantes.', 'Los derechos de voto deben ser sustantivos, no meramente protectores (ver abajo).']
      },
      {
        heading: 'Poder II: control de hecho',
        paragraphs: [
          'El control de hecho surge cuando un inversor posee menos de la mitad de los votos pero puede aun así dirigir la participada en la práctica. El patrón clásico: el inversor posee el 45 %, y el 55 % restante está disperso entre miles de pequeños accionistas que históricamente no votan o nunca se coordinan. Si el tenedor del 45 % ha ganado sistemáticamente cada votación de accionistas, tiene poder — de hecho, pero poder al fin.',
          'La NIIF 10 enumera la evidencia a ponderar: el tamaño de la participación en relación con la dispersión de los demás, los patrones históricos de voto, los derechos de voto potenciales, y cualquier acuerdo contractual. El control de hecho es una cuestión de juicio, y los auditores lo indagan a fondo, porque consolidar (o no consolidar) sobre esta base transforma el tamaño informado del grupo.'
        ],
        callout: { type: 'example', text: 'HoldCo posee el 42 % de OpCo. El otro 58 % lo poseen 3.000 inversores minoristas; la asistencia a las juntas generales nunca ha superado el 30 % de los votos totales, y los candidatos de HoldCo siempre han sido elegidos. HoldCo tiene poder de hecho y consolida OpCo — aunque posee menos de la mitad.' }
      },
      {
        heading: 'Derechos de voto potenciales y el test principal-frente a-agente',
        paragraphs: [
          'Los derechos de voto potenciales — opciones, warrants, bonos convertibles — cuentan para el poder solo si son sustantivos: actualmente ejercitables (o ejercitables cuando se toman decisiones sobre las actividades relevantes), y económicamente sensato ejercerlos (las opciones muy fuera de dinero que nadie ejercería se ignoran). Un tenedor del 40 % con opciones actualmente ejercitables sobre otro 15 % posee efectivamente el poder.',
          'Después está la cuestión principal-frente a-agente. Un decisor (por ejemplo un gestor de fondos) podría parecer que dirige las actividades relevantes, pero si actúa en nombre de otros — si su discrecionalidad es estrecha, su remuneración es de mercado sin variabilidad real, y los inversores poseen derechos sustantivos de destitución — es un agente, no un principal, y no controla. Los derechos de destitución en manos de una sola parte pesan fuertemente hacia la agencia; los derechos ejercitables solo por una mayoría dispersa pesan menos.'
        ],
        bullets: ['Derechos de voto potenciales sustantivos: actualmente ejercitables y económicamente racional ejercerlos.', 'Los derechos protectores (veto sobre emitir nuevas acciones, aprobar la venta de todo el negocio) protegen una inversión; no dan poder.', 'Indicadores de agente: ámbito de decisión estrecho, remuneración fija a tipo de mercado, derechos sustantivos de destitución en manos de otros.']
      },
      {
        heading: 'Entidades estructuradas',
        paragraphs: [
          'Una entidad estructurada está diseñada de modo que los derechos de voto o similares no sean el factor dominante para decidir quién la controla — los derechos de voto pueden referirse solo a tareas administrativas mientras las actividades relevantes se dirigen por acuerdos contractuales. Pensar en vehículos de titulización, conductos de financiación respaldados por activos, o ciertos fondos de inversión: los contratos (quién gestiona los activos, quién absorbe las primeras pérdidas, quién decide sobre los impagos) determinan el control, no la urna.',
          'Para las entidades estructuradas, el análisis del control se centra en el propósito y diseño de la entidad, qué parte dirigió su constitución, qué derechos contractuales rigen las actividades relevantes, y quién está más expuesto a los rendimientos variables. Los patrocinadores que diseñaron el vehículo, gestionan sus activos y retienen el tramo de patrimonio muy a menudo lo controlan — que es exactamente por lo que existe la norma: para impedir que los riesgos se aparquen fuera de balance en vehículos que el patrocinador dirige efectivamente.'
        ],
        callout: { type: 'warning', text: 'Cuando los derechos de voto son irrelevantes por diseño, mirar los contratos. La parte que diseñó el vehículo, dirige sus actividades relevantes contractualmente, y toma los rendimientos variables normalmente lo controla.' },
        table: { headers: ['Situación', 'Conclusión probable de control', 'Por qué'], rows: [['55 % de derechos de voto, sin restricciones', 'Control — consolidar', 'Poder + rendimientos variables + vínculo todos presentes'], ['42 %, otros dispersos, siempre gana las votaciones', 'Control de hecho — consolidar', 'Poder en la práctica a pesar de <50 %'], ['Opción actualmente ejercitable que lleva la participación al 60 %', 'Control — consolidar', 'Los derechos de voto potenciales sustantivos dan poder'], ['Gestor de fondos, los inversores pueden destituirlo a voluntad', 'Sin control — agente', 'Actúa para otros; los derechos de destitución indican agencia'], ['Patrocinador de un vehículo de titulización, gestiona activos, posee el tramo de patrimonio', 'Control — consolidar', 'Poder contractual + rendimientos variables en una entidad estructurada']] }
      },
      {
        heading: 'Pérdida del control y reevaluación',
        paragraphs: [
          'El control no es un veredicto único: la NIIF 10 exige reevaluación siempre que cambian los hechos — un nuevo acuerdo de accionistas, opciones que expiran, una dilución por ampliación de capital, o un regulador que interviene. Cuando se pierde el control, la contabilidad es decisiva: dar de baja los activos y pasivos de la filial (incluida cualquier PND y el fondo de comercio relacionado), reconocer cualquier participación retenida a valor razonable en la fecha en que se pierde el control, y reconocer la ganancia o pérdida resultante en resultados.',
          'Esa ganancia o pérdida puede ser grande, porque la participación retenida se revalora a valor razonable aunque nada se haya vendido — por ejemplo cuando una filial emite nuevas acciones a un tercero y la matriz se diluye del 60 % al 40 %. Desde esa fecha la antigua filial se convierte en una asociada, un acuerdo conjunto, o un activo financiero, y la puesta en equivalencia o el valor razonable toman el relevo.'
        ],
        journal: {
          transaction: 'Pérdida del control: matriz diluida del 60 % al 40 %; la participación retenida del 40 % tiene un valor razonable de $300,000; el importe en libros de los activos netos dados de baja (tras la PND) es $260,000',
          lines: [
            { account: 'Inversión en asociada (40 % a valor razonable)', dr: 300000, cr: null },
            { account: 'Activos netos de la antigua filial (importe en libros)', dr: null, cr: 260000 },
            { account: 'Ganancia por pérdida del control (resultados)', dr: null, cr: 40000 }
          ],
          narration: 'Al perder el control, dar de baja los activos netos de la filial y revalorar la participación retenida a valor razonable; la diferencia de $40,000 es una ganancia en resultados.'
        },
        impact: { pl: 'Una ganancia de $40,000 se reconoce en resultados en la fecha en que se pierde el control.', bs: 'Los activos/pasivos de la filial salen del balance; aparece una inversión en asociada de $300,000.', cf: 'Sin efecto en efectivo cuando el control se pierde por dilución sin venta.' }
      }
    ],
    mistakes: [
      'Suponer que el 51 % siempre significa control — los derechos de voto potenciales sustantivos en manos de otros, o una relación de agencia, pueden derrotarlo.',
      'Tratar los derechos protectores (veto sobre cambios fundamentales) como poder: protegen una inversión pero no dirigen las actividades relevantes.',
      'Ignorar el control de hecho: una participación del 42 % que siempre gana las votaciones de accionistas es poder en el fondo.',
      'Olvidar las entidades estructuradas, donde los derechos de voto son irrelevantes y los contratos deciden.',
      'No reevaluar nunca el control tras una ampliación de capital, opciones expiradas, o un nuevo acuerdo de accionistas.',
      'En la pérdida del control, olvidar revalorar la participación retenida a valor razonable — la ganancia o pérdida suele pasarse por alto.'
    ],
    interviewQA: [
      { q: '¿Cuáles son los tres elementos del control bajo la NIIF 10?', a: 'Poder sobre la participada — derechos existentes que dan la capacidad actual de dirigir las actividades relevantes; exposición o derechos a rendimientos variables por la implicación, como dividendos, sinergias, o ahorros de costes; y la capacidad de usar ese poder para afectar al importe de los rendimientos. Los tres deben estar presentes simultáneamente. Añadiría que la evaluación es continua: si cambian los hechos — nuevos acuerdos, opciones que expiran, dilución — el control debe reevaluarse.' },
      { q: 'Dar un ejemplo de control de hecho.', a: 'Un inversor posee el 45 % de una cotizada mientras que el 55 % restante está disperso entre miles de accionistas minoristas que rara vez votan. Si el tenedor del 45 % ha nombrado históricamente al consejo y ganado cada votación, tiene poder de hecho a pesar de poseer menos de la mitad. La NIIF 10 exige ponderar el tamaño relativo de la participación, la dispersión de los demás tenedores, y el historial de voto — es una cuestión de juicio, y una que los auditores impugnan, porque decide si la entidad se consolida.' },
      { q: '¿Qué es una entidad estructurada, y por qué la NIIF 10 la destaca?', a: 'Una entidad estructurada está diseñada de modo que los derechos de voto no sean el factor dominante — pueden cubrir solo tareas administrativas mientras los contratos dirigen las actividades relevantes. Ejemplos son los vehículos de titulización y los conductos de financiación. La norma las destaca porque los patrocinadores solían aparcar riesgos fuera de balance en vehículos que dirigían efectivamente. El test de control mira el propósito y diseño del vehículo, quién dirige las actividades contractualmente, y quién toma los rendimientos variables — a menudo el patrocinador que lo constituyó y posee el tramo de patrimonio.' }
    ],
    quiz: [
      { question: 'Bajo la NIIF 10, un inversor controla una participada cuando tiene:', options: ['Más del 50 % de las acciones, con independencia de cualquier otro hecho', 'Solo exposición a rendimientos variables', 'Solo poder sobre la participada', 'Poder sobre la participada, exposición a rendimientos variables, y la capacidad de usar su poder para afectar a dichos rendimientos'], answer: 3, explanation: 'Los tres elementos son acumulativos: poder, rendimientos variables, y el vínculo entre ellos. Una participación mayoritaria es solo evidencia de poder, no todo el test.', difficulty: 'Foundation', topic: 'Control Definition', skill: 'Consolidation' },
      { question: '¿Cuál de los siguientes es un ejemplo de rendimiento variable?', options: ['Un salario fijo pagado a la recepcionista de la participada', 'Dividendos que suben y bajan con el rendimiento de la participada', 'Un préstamo bancario a tipo de interés fijo concedido a la participada', 'El alquiler de oficinas pagado por la participada a un arrendador tercero'], answer: 1, explanation: 'Los rendimientos variables varían con el rendimiento: dividendos, ahorros de costes, sinergias, economías de escala, o intereses residuales. Los flujos contractuales fijos a terceros no son los rendimientos variables del inversor.', difficulty: 'Foundation', topic: 'Variable Returns', skill: 'Consolidation' },
      { question: 'El inversor posee el 45 % de la objetivo. El otro 55 % lo poseen miles de pequeños inversores que nunca votan, y el inversor ha nombrado al consejo durante cinco años consecutivos. La conclusión correcta es:', options: ['Sin control — el 45 % es menos de la mitad, por lo que aplica la puesta en equivalencia', 'Control solo si el inversor compra otro 6 %', 'Control conjunto con los pequeños inversores', 'El inversor tiene control de hecho y consolida la objetivo'], answer: 3, explanation: 'El poder se evalúa en el fondo: un tenedor del 45 % que dirige sistemáticamente la participada porque las demás participaciones están dispersas y son pasivas tiene poder de hecho, por tanto control.', difficulty: 'Intermediate', topic: 'De Facto Control', skill: 'Consolidation' },
      { question: 'Un inversor posee el 40 % de los votos más opciones, ejercitables hoy a un precio sensato, sobre otro 20 %. ¿Cómo afectan las opciones a la evaluación del control?', options: ['Se ignoran porque no se han ejercido', 'Dan control conjunto con el emisor de la opción', 'Son derechos de voto potenciales sustantivos y dan al inversor el poder (60 % efectivo)', 'Solo importan si el inversor ya posee el 50 %'], answer: 2, explanation: 'Las opciones actualmente ejercitables en condiciones sensatas son derechos de voto potenciales sustantivos: el inversor tiene actualmente la capacidad de alcanzar el 60 % de los votos, lo que es poder.', difficulty: 'Intermediate', topic: 'Potential Voting Rights', skill: 'Consolidation' },
      { question: 'Un gestor de fondos dirige las inversiones de un fondo, cobra una comisión fija a tipo de mercado, y los inversores pueden destituir al gestor en cualquier momento sin causa. El gestor:', options: ['Es un agente y no controla el fondo', 'Controla el fondo porque dirige las actividades relevantes', 'Controla conjuntamente el fondo con los inversores', 'Controla el fondo solo si también invierte su propio dinero'], answer: 0, explanation: 'Los derechos sustantivos de destitución, la discrecionalidad estrecha, y la remuneración a tipo de mercado sin variabilidad real apuntan a una relación de agencia: el gestor actúa para los inversores y no controla.', difficulty: 'Intermediate', topic: 'Principal vs Agent', skill: 'Consolidation' },
      { question: '¿Qué derecho es protector en lugar de dar poder?', options: ['El derecho a nombrar a la mayoría del consejo', 'El veto de un prestamista sobre que el prestatario venda todo su negocio', 'El derecho a aprobar el presupuesto anual', 'El derecho a dirigir las políticas operativas del día a día'], answer: 1, explanation: 'Los derechos protectores protegen una inversión contra cambios fundamentales; no dan la capacidad actual de dirigir las actividades relevantes, por lo que no confieren poder.', difficulty: 'Intermediate', topic: 'Power', skill: 'Consolidation' },
      { question: 'Un banco patrocina un vehículo de titulización: diseñó el vehículo, gestiona los préstamos subyacentes bajo contrato, y posee el tramo de patrimonio de primeras pérdidas. Los derechos de voto cubren solo asuntos administrativos. El banco:', options: ['Controla el vehículo y lo consolida', 'No lo controla porque no posee mayoría de voto', 'Tiene solo influencia significativa', 'Debe tratar el vehículo como un negocio conjunto'], answer: 0, explanation: 'En una entidad estructurada, los contratos — no los votos — dirigen las actividades relevantes. El patrocinador que diseñó el vehículo, lo dirige contractualmente, y toma los rendimientos variables (tramo de primeras pérdidas) lo controla.', difficulty: 'Advanced', topic: 'Structured Entities', skill: 'Consolidation' },
      { question: 'Si solo están presentes dos de los tres elementos del control (digamos, poder y rendimientos variables, pero el inversor es un agente que actúa para otros):', options: ['Hay control — dos de tres basta', 'Hay control conjunto', 'No hay control', 'Hay control solo si la propiedad supera el 50 %'], answer: 2, explanation: 'Los tres elementos son acumulativos. Un agente puede tener poder aparente e incluso algunos rendimientos, pero sin la capacidad de usar el poder para su propio beneficio no hay control.', difficulty: 'Foundation', topic: 'Control Definition', skill: 'Consolidation' },
      { question: 'Al perder el control de una filial reteniendo una participación del 40 %, la contabilidad correcta incluye:', options: ['Mantener la participación retenida a su antiguo importe en libros sin efecto en resultados', 'Revalorar la participación retenida del 40 % a valor razonable y reconocer una ganancia o pérdida en resultados', 'Reconocer la participación retenida al coste histórico de la inversión original', 'Reducir la participación retenida a cero'], answer: 1, explanation: 'La NIIF 10 exige dar de baja los activos, pasivos y PND de la filial, reconocer cualquier participación retenida a valor razonable en la fecha en que se pierde el control, y una ganancia o pérdida en resultados por la diferencia.', difficulty: 'Advanced', topic: 'Loss of Control', skill: 'Consolidation' }
    ]
  },
  {
    id: 'm24', level: 6, levelTitle: 'Group Accounting', title: 'NIIF 3 — Combinaciones de negocios',
    standard: 'IFRS 3', tagline: 'Comprar un negocio, no solo activos: el método de adquisición en cuatro pasos.',
    description: 'La NIIF 3 regula cómo contabiliza un adquirente la compra del control de un negocio. Este módulo recorre el método de adquisición — identificar al adquirente, valorar la contraprestación a valor razonable, reconocer los activos netos identificables a valor razonable, y calcular el fondo de comercio o la ganancia por compra ventajosa — con casos de adquisición simplificados que pueden seguirse línea a línea.',
    minutes: 22, skills: ['Consolidation'],
    sections: [
      {
        heading: '¿Qué cuenta como combinación de negocios?',
        paragraphs: [
          'Una combinación de negocios es una transacción en la que un adquirente obtiene el control de un negocio. Y un negocio no es solo un montón de activos: es un conjunto integrado de actividades y activos — insumos y procesos sustantivos — capaz de producir productos. Comprar una sola máquina es una compra de activos; comprar una fábrica con su plantilla, contratos y procesos de producción es una combinación de negocios.',
          'Por qué importa la distinción: solo las combinaciones de negocios usan el método de adquisición con fondo de comercio. Una compra de activos simplemente asigna el coste a los activos comprados, sin fondo de comercio ni ganancia por compra ventajosa. La NIIF 3 incluso proporciona un test de concentración opcional: si sustancialmente todo el valor razonable se concentra en un solo activo (o grupo de activos similares), el conjunto no es un negocio y el test puede atajar el análisis.'
        ],
        callout: { type: 'key', text: 'Negocio = insumos + procesos sustantivos capaces de crear productos. Sin procesos sustantivos, no hay negocio — y no hay fondo de comercio.' }
      },
      {
        heading: 'El método de adquisición en cuatro pasos',
        paragraphs: [
          'Cada combinación de negocios bajo la NIIF 3 sigue los mismos cuatro pasos. Paso 1: identificar al adquirente — la entidad que obtiene el control (normalmente, pero no siempre, la que paga). Paso 2: determinar la fecha de adquisición — la fecha en que el control pasa realmente, porque fija todas las valoraciones a valor razonable. Paso 3: reconocer y valorar los activos identificables adquiridos y los pasivos asumidos a sus valores razonables en la fecha de adquisición — incluidos activos intangibles como relaciones con clientes y marcas que la objetivo nunca reconoció, siempre que sean identificables. Paso 4: reconocer y valorar el fondo de comercio o una ganancia por compra ventajosa como residual.',
          'Dos principios de reconocimiento hacen exigente el paso 3: identificable significa separable (podría venderse por sí solo) o derivado de derechos contractuales/legales; y todo se valora a valor razonable en la fecha de adquisición — no a los antiguos valores contables de la objetivo. Los pasivos contingentes también se reconocen, si son obligaciones presentes valorables a valor razonable, lo que es más estricto que el tratamiento normal de la NIC 37.'
        ],
        steps: ['Paso 1 — Identificar al adquirente: ¿quién obtuvo el control?', 'Paso 2 — Fijar la fecha de adquisición: ¿cuándo pasó el control?', 'Paso 3 — Reconocer los activos y pasivos identificables a valor razonable en la fecha de adquisición.', 'Paso 4 — Calcular el fondo de comercio (o una ganancia por compra ventajosa) como residual.']
      },
      {
        heading: 'Valoración del fondo de comercio',
        paragraphs: [
          'El fondo de comercio es la prima pagada por lo que no puede identificarse por separado: la plantilla organizada, el valor de empresa en funcionamiento, las sinergias esperadas. La fórmula es mecánica: Fondo de comercio = contraprestación transferida − valor razonable de los activos netos identificables adquiridos (con ajustes de PND cuando la participación es inferior al 100 %, cubierto en m22). La contraprestación se valora a valor razonable e incluye efectivo, acciones emitidas (a su valor razonable en la fecha de adquisición), y contraprestación contingente (earn-outs) a valor razonable.',
          'Tres reglas en los bordes: los costes relacionados con la adquisición — honorarios jurídicos, due diligence, asesoramiento — se llevan a gastos, nunca se añaden a la contraprestación ni al fondo de comercio. La contraprestación contingente clasificada como pasivo se revalora a valor razonable en cada fecha de cierre con cambios en resultados; clasificada como patrimonio, no se revalora. Y en una adquisición por etapas, cualquier participación en el patrimonio poseída previamente se revalora a valor razonable en la fecha de adquisición, con la ganancia o pérdida en resultados.'
        ],
        journal: {
          transaction: 'Adquisición: la matriz paga $500,000 en efectivo por el 100 % de la objetivo; los activos netos identificables tienen un valor razonable de $420,000',
          lines: [
            { account: 'Activos netos identificables (a valor razonable)', dr: 420000, cr: null },
            { account: 'Fondo de comercio ($500,000 − $420,000)', dr: 80000, cr: null },
            { account: 'Efectivo', dr: null, cr: 500000 }
          ],
          narration: 'Aplicar el método de adquisición: reconocer lo identificable a valor razonable; el residual de $80,000 es fondo de comercio.'
        },
        impact: { pl: 'Sin efecto en resultados el primer día (los costes de transacción, si los hay, se llevan a gastos por separado).', bs: 'Activos netos aumentan $420,000 a valor razonable; activo por fondo de comercio de $80,000 reconocido.', cf: 'Salida de efectivo de $500,000 en actividades de inversión.' },
        callout: { type: 'warning', text: 'Los costes relacionados con la adquisición (abogados, asesores, due diligence) se llevan a gastos. Añadirlos al fondo de comercio es uno de los errores más comunes de la NIIF 3.' }
      },
      {
        heading: 'Compras ventajosas: cuando se paga menos que el valor razonable',
        paragraphs: [
          'A veces el precio está por debajo del valor razonable de los activos netos — una venta forzosa, un vendedor obligado, una subasta mal valorada. Antes de celebrar, la NIIF 3 exige una reevaluación: comprobar que todos los activos y pasivos identificables fueron capturados y correctamente valorados. Si la ganga sobrevive a esa revisión, la diferencia se reconoce inmediatamente como ganancia en resultados.',
          'Una ganancia por compra ventajosa no se difiere, no se aparca en el patrimonio neto, y no se netea contra los activos. Va directamente a resultados en la fecha de adquisición. Económicamente significa que el adquirente compró $420,000 de valor neto por $380,000 — el descuento de $40,000 es ingreso, porque el grupo es $40,000 más rico en el momento en que pasa el control.'
        ],
        journal: {
          transaction: 'Compra ventajosa: la matriz paga $380,000 en efectivo por el 100 % de la objetivo; los activos netos identificables tienen un valor razonable de $420,000 (tras la reevaluación)',
          lines: [
            { account: 'Activos netos identificables (a valor razonable)', dr: 420000, cr: null },
            { account: 'Efectivo', dr: null, cr: 380000 },
            { account: 'Ganancia por compra ventajosa (resultados)', dr: null, cr: 40000 }
          ],
          narration: 'Tras reevaluar todas las valoraciones, el exceso de $40,000 del valor razonable sobre la contraprestación se reconoce como ganancia en resultados.'
        },
        impact: { pl: 'Una ganancia de $40,000 aumenta el resultado en la fecha de adquisición.', bs: 'Activos netos de $420,000 reconocidos; sin fondo de comercio.', cf: 'Salida de efectivo de $380,000 en actividades de inversión.' }
      },
      {
        heading: 'Contraprestación transferida: efectivo, acciones y earn-outs',
        paragraphs: [
          'La contraprestación es lo que el adquirente entrega, valorado a valor razonable en la fecha de adquisición. El efectivo es simple. Las acciones emitidas se valoran a su precio de mercado en la fecha de adquisición — no al nominal, no a algún valor negociado. La contraprestación contingente (earn-outs pagaderos si la objetivo alcanza objetivos de beneficio) se valora a valor razonable en la fecha de adquisición, lo que significa estimar probabilidades y descontar, no esperar a ver qué pasa.',
          'La clasificación de la contraprestación contingente determina su vida posterior: los earn-outs clasificados como pasivo se revaloran cada periodo a través de resultados (por lo que una objetivo que supera las expectativas crea gasto adicional), mientras que los earn-outs clasificados como patrimonio (un número fijo de acciones a emitir) quedan congelados a valor razonable en la fecha de adquisición. Acertar esta clasificación el primer día evita años de incorrección.'
        ],
        table: { headers: ['Forma de contraprestación', 'Valorada a', 'Tratamiento posterior'], rows: [['Efectivo pagado', 'Importe pagado', 'Ninguno — hecho'], ['Acciones emitidas', 'Valor razonable en la fecha de adquisición', 'Ninguno — patrimonio'], ['Contraprestación contingente (pasivo)', 'Valor razonable en la fecha de adquisición', 'Revalorada a través de resultados cada periodo'], ['Contraprestación contingente (patrimonio)', 'Valor razonable en la fecha de adquisición', 'No revalorada'], ['Honorarios de asesoramiento y jurídicos', '—', 'Llevados a gastos inmediatamente, nunca parte de la contraprestación']] }
      },
      {
        heading: 'Caso de adquisición simplificado: unir las piezas',
        paragraphs: [
          'Alpha paga $500,000 en efectivo por el 100 % de Beta el 1 de marzo. Los libros de Beta muestran activos netos de $350,000, pero una valoración encuentra: un intangible de relaciones con clientes por $40,000 que Beta nunca reconoció, y existencias revalorizadas $30,000 a valor razonable. Activos netos identificables a valor razonable = $350,000 + $40,000 + $30,000 = $420,000. Fondo de comercio = $500,000 − $420,000 = $80,000 — exactamente el asiento de la sección de fondo de comercio anterior.',
          'Observar lo que hizo el ejercicio de valor razonable: $70,000 de la aparente prima de $150,000 era en realidad valor identificable (intangibles, revalorización de existencias), dejando solo $80,000 de fondo de comercio verdadero. Las asignaciones descuidadas del precio de compra lo vuelcan todo al fondo de comercio; las buenas identifican primero los intangibles, porque el fondo de comercio — a diferencia de un intangible de relaciones con clientes — no puede amortizarse y no dice a los inversores nada sobre lo que realmente se compró.'
        ],
        callout: { type: 'interview', text: 'A los entrevistadores les encanta: "¿Por qué los adquirentes prefieren identificar intangibles antes que dejar valor en el fondo de comercio?" Porque los intangibles identificables con vidas finitas se amortizan sistemáticamente, mientras que el fondo de comercio solo se somete a test de deterioro — y porque la asignación revela lo que realmente se compró (marcas, relaciones, tecnología) en lugar de ocultarlo en un residual.' }
      }
    ],
    mistakes: [
      'Valorar la contraprestación a valores contables o negociados en lugar de a valor razonable en la fecha de adquisición.',
      'Capitalizar los costes relacionados con la adquisición (jurídicos, asesoramiento, due diligence) en el fondo de comercio — deben llevarse a gastos.',
      'Reconocer fondo de comercio en una compra de activos que no es un negocio; ejecutar primero el test de concentración.',
      'Reconocer una ganancia por compra ventajosa antes de la reevaluación obligatoria de activos, pasivos y contraprestación.',
      'Usar los antiguos importes en libros de la objetivo en lugar de los valores razonables en la fecha de adquisición para los activos netos identificables.',
      'Olvidar revalorar a valor razonable una participación en el patrimonio poseída previamente en una adquisición por etapas.'
    ],
    interviewQA: [
      { q: '¿Cómo se calcula el fondo de comercio bajo la NIIF 3?', a: 'El fondo de comercio es el residual: contraprestación transferida (valorada a valor razonable, incluidas acciones a valor de mercado y contraprestación contingente a valor razonable) menos el valor razonable en la fecha de adquisición de los activos netos identificables adquiridos. En una adquisición parcial, la elección de valoración de la PND afecta a la cifra. Captura lo que no puede identificarse por separado — sinergias, la plantilla organizada, el valor de empresa en funcionamiento. Una disciplina útil es identificar primero los intangibles (marcas, relaciones con clientes, tecnología), para que el fondo de comercio sea un verdadero residual y no un vertedero.' },
      { q: '¿Qué es una compra ventajosa y adónde va la ganancia?', a: 'Una compra ventajosa ocurre cuando el valor razonable de los activos netos identificables supera la contraprestación transferida — normalmente una venta forzosa o con dificultades. La NIIF 3 exige primero una reevaluación para confirmar que nada se omitió o valoró mal. Si la ganga se mantiene, la diferencia se reconoce inmediatamente como ganancia en resultados, no diferida ni aparcada en el patrimonio. Económicamente, el grupo es más rico en ese importe en el momento en que pasa el control.' },
      { q: '¿Por qué los costes relacionados con la adquisición se llevan a gastos en lugar de incluirse en el fondo de comercio?', a: 'Porque no forman parte de lo que el adquirente entrega por el negocio — son transacciones separadas por servicios consumidos (asesoramiento jurídico, due diligence). Incluirlos en la contraprestación inflaría el fondo de comercio con costes que no tienen beneficio económico futuro. La NIIF 3 es explícita: los costes de transacción se llevan a gastos cuando se incurren, lo que también impide a los adquirentes enterrar honorarios en un residual no amortizable.' }
    ],
    quiz: [
      { question: '¿Qué transacción es una combinación de negocios bajo la NIIF 3?', options: ['Comprar una furgoneta de reparto al contado', 'Comprar un terreno como inversión', 'Amortizar un préstamo bancario', 'Adquirir el control de una fábrica con su plantilla, contratos y procesos de producción'], answer: 3, explanation: 'Un negocio necesita insumos y procesos sustantivos capaces de producir productos. Una fábrica con plantilla y procesos cualifica; los activos individuales no, y se contabilizan como compras de activos sin fondo de comercio.', difficulty: 'Foundation', topic: 'Scope', skill: 'Consolidation' },
      { question: 'La matriz paga $500,000 en efectivo por el 100 % de la objetivo. Los activos netos identificables tienen un valor razonable de $420,000. El fondo de comercio es:', options: ['$500,000', '$80,000', '$420,000', '$920,000'], answer: 1, explanation: 'Fondo de comercio = contraprestación transferida − valor razonable de los activos netos identificables = $500,000 − $420,000 = $80,000.', difficulty: 'Intermediate', topic: 'Goodwill Measurement', skill: 'Consolidation' },
      { question: 'La matriz paga $380,000 por activos netos con un valor razonable de $420,000 (tras la reevaluación). El tratamiento correcto es:', options: ['Reconocer $40,000 de fondo de comercio negativo como activo', 'Diferir los $40,000 y amortizarlos en cinco años', 'Reconocer una ganancia de $40,000 en resultados', 'Reducir los importes en libros de los activos adquiridos en $40,000'], answer: 2, explanation: 'Tras la reevaluación obligatoria, una ganancia por compra ventajosa va inmediatamente a resultados. Nunca se difiere, se netea contra activos, ni se llama fondo de comercio negativo.', difficulty: 'Intermediate', topic: 'Bargain Purchase', skill: 'Consolidation' },
      { question: 'Los honorarios jurídicos y de asesoramiento de $25,000 incurridos en una adquisición son:', options: ['Añadidos al fondo de comercio', 'Añadidos a la contraprestación transferida', 'Capitalizados como activo intangible', 'Llevados a gastos en resultados'], answer: 3, explanation: 'La NIIF 3 exige llevar a gastos los costes relacionados con la adquisición cuando se incurren; son servicios consumidos, no parte del precio pagado por el negocio.', difficulty: 'Foundation', topic: 'Acquisition Method', skill: 'Consolidation' },
      { question: 'El adquirente emite 10.000 acciones como contraprestación. Las acciones cotizan a $32 en la fecha de adquisición. La contraprestación incluye:', options: ['$320,000 valorados al precio de mercado en la fecha de adquisición', '$100,000 valorados al nominal de $10', 'Nada — la contraprestación en acciones solo se revela', 'El valor que las partes negociaron privadamente'], answer: 0, explanation: 'La contraprestación en acciones se valora a valor razonable en la fecha de adquisición — el precio de mercado de $32 — no al nominal ni a una cifra negociada.', difficulty: 'Intermediate', topic: 'Consideration', skill: 'Consolidation' },
      { question: 'La contraprestación contingente (un earn-out) clasificada como pasivo es:', options: ['Congelada a valor razonable en la fecha de adquisición para siempre', 'Revalorada a valor razonable en cada fecha de cierre con cambios en resultados', 'Amortizada durante el periodo del earn-out', 'Reconocida solo cuando el earn-out se paga realmente'], answer: 1, explanation: 'La contraprestación contingente clasificada como pasivo es un pasivo financiero revalorado a través de resultados cada periodo — una objetivo que supera las expectativas crea gasto adicional. La contraprestación contingente clasificada como patrimonio no se revalora.', difficulty: 'Advanced', topic: 'Contingent Consideration', skill: 'Consolidation' },
      { question: '¿Cuál de los siguientes NO forma parte de la contraprestación transferida?', options: ['Efectivo pagado al vendedor', 'Acciones emitidas al vendedor', 'Contraprestación contingente a valor razonable', 'Honorarios de due diligence pagados a asesores externos'], answer: 3, explanation: 'Los costes de transacción por servicios (due diligence, jurídicos, asesoramiento) se llevan a gastos por separado. La contraprestación es lo que se entrega por el negocio en sí: efectivo, acciones, y pagos contingentes.', difficulty: 'Intermediate', topic: 'Consideration', skill: 'Consolidation' },
      { question: 'En una adquisición por etapas, la matriz ya poseía el 20 % de la objetivo y ahora compra otro 40 %, obteniendo el control. La participación del 20 % poseída previamente es:', options: ['Revalorada a valor razonable en la fecha de adquisición, con la ganancia o pérdida en resultados', 'Mantenida a su coste original sin revaloración', 'Dada de baja contra el fondo de comercio', 'Transferida a la PND'], answer: 0, explanation: 'Lograr el control se trata como enajenar la antigua participación y readquirirla: la participación en el patrimonio poseída previamente se revalora a valor razonable en la fecha de adquisición, y la diferencia va a resultados.', difficulty: 'Advanced', topic: 'Step Acquisition', skill: 'Consolidation' },
      { question: 'Bajo la definición modificada de la NIIF 3, un conjunto de actividades y activos es un negocio si incluye:', options: ['Insumos, procesos y productos reales — los tres son obligatorios', 'Solo productos, como ingresos existentes', 'Insumos y procesos sustantivos que juntos son capaces de producir productos', 'Cualquier grupo de activos comprados juntos'], answer: 2, explanation: 'Los productos ya no son estrictamente necesarios: insumos más procesos sustantivos capaces de crear productos bastan. Por eso una empresa de I+D en fase inicial sin ingresos puede seguir siendo un negocio.', difficulty: 'Foundation', topic: 'Scope', skill: 'Consolidation' }
    ]
  },
  {
    id: 'm25', level: 6, levelTitle: 'Group Accounting', title: 'Contabilidad intragrupo',
    standard: 'IFRS 10', tagline: 'Si A dice 150.000 y B dice 145.000, alguien está equivocado — averiguar quién.',
    description: 'Antes de que las eliminaciones de consolidación puedan funcionar, los saldos intragrupo deben coincidir. Este módulo se construye alrededor de un caso real: la cuenta a cobrar intragrupo de la empresa A de $150,000 contra la cuenta a pagar de la empresa B de $145,000. Se ejecutará la investigación, se aprenderán las cinco causas clásicas de descuadres, y se verá cómo el proceso de conciliación y confirmación los previene.',
    minutes: 16, skills: ['Consolidation', 'Month-End Closing'],
    sections: [
      {
        heading: 'Por qué lo intragrupo debe cuadrar primero',
        paragraphs: [
          'Las eliminaciones de consolidación asumen imágenes espejo: la cuenta a cobrar de A a B equivale a la cuenta a pagar de B a A. Cuando no coinciden, la eliminación no puede registrarse limpiamente — y la diferencia nunca es solo un error de redondeo que pueda ignorarse. Un descuadre persistente significa que una transacción fue registrada por una parte y no por la otra, registrada dos veces, registrada en la moneda equivocada, o registrada contra la contraparte equivocada. Cada uno de esos es o un error en los estados financieros separados de alguien o, en el peor caso, una ocultación.',
          'Por eso los grupos ejecutan la conciliación intragrupo como una puerta dura en el cierre: sin consolidación hasta que las diferencias intragrupo materiales se investigan y resuelven. La disciplina también protege los estados financieros separados — los auditores de la empresa A y los de la empresa B dependen cada uno de que estos saldos sean correctos.'
        ],
        callout: { type: 'key', text: 'Las diferencias intragrupo nunca se tapan con un ajuste. Se investigan, se explican y se corrigen — porque cada una es un error (o peor) en los libros de alguien.' }
      },
      {
        heading: 'El caso: $150,000 frente a $145,000',
        paragraphs: [
          'Cierre de mes. La empresa A informa una cuenta a cobrar intragrupo de la empresa B de $150,000. La empresa B informa una cuenta a pagar intragrupo a la empresa A de $145,000. La diferencia de $5,000 bloquea la consolidación. Su trabajo: encontrarla. La investigación sigue una secuencia fija — nunca empezar adivinando, y nunca empezar registrando un ajuste.',
          'Primero, obtener los libros detallados: el submayor de A de facturas emitidas a B, y el submayor de B de facturas recibidas de A, con fechas, importes, monedas y números de documento. Segundo, comparar transacción por transacción y aislar las partidas sin conciliar. Tercero, para cada partida sin conciliar, determinar la causa entre las cinco clásicas de abajo. Cuarto, registrar la corrección en los libros de la entidad correcta. Quinto, reejecutar la conciliación y confirmar que ambas partes coinciden ahora en $150,000.'
        ],
        steps: ['Paso 1 — Obtener ambos submayores detallados (cuentas a cobrar de A, cuentas a pagar de B) con números de documento y fechas.', 'Paso 2 — Conciliar transacción por transacción; aislar cada partida sin conciliar.', 'Paso 3 — Diagnosticar cada partida sin conciliar contra las cinco causas clásicas.', 'Paso 4 — Registrar la corrección en la entidad correcta — nunca un ajuste tapón en la consolidación.', 'Paso 5 — Reejecutar la conciliación; ambas partes deben coincidir antes de que la consolidación proceda.'],
        callout: { type: 'example', text: 'La conciliación aísla una partida: A emitió la factura INV-2291 por $5,000 (soporte IT, diciembre) que aparece en el libro de A pero en ningún lugar en el de B. Diagnóstico: factura no registrada — B nunca la registró. Resolución: B registra Debe Gasto de soporte IT $5,000 / Haber Cuenta a pagar intragrupo — A $5,000. Ambas partes coinciden ahora en $150,000.' }
      },
      {
        heading: 'Las cinco causas clásicas',
        paragraphs: [
          'Casi cada descuadre intragrupo se remonta a una de cinco causas. Aprender a reconocer la firma de cada una y se resolverán la mayoría de los casos en minutos. La tabla de abajo merece memorizarse — es también, casi literalmente, lo que preguntan los entrevistadores.'
        ],
        table: { headers: ['Causa', 'Firma', 'Corrección'], rows: [['Factura no registrada / transacción no contabilizada', 'En el libro de A, ausente en el de B (o viceversa)', 'La parte que falta registra la transacción'], ['Diferencia temporal', 'Registrada por ambas, en periodos diferentes (p. ej., mercancías enviadas el 31 dic, recibidas el 2 ene)', 'Sin corrección — documentar la diferencia temporal; se autoresuelve'], ['Efectivo en tránsito', 'A pagó el 31 dic; el banco de B lo muestra el 3 ene', 'Sin corrección — revelar como en tránsito; confirmar la recepción'], ['Diferencias de cambio', 'Los importes coinciden en la moneda de transacción pero difieren tras la conversión', 'Cada parte registra su ganancia/pérdida de cambio; acordar la fuente del tipo y el momento'], ['Registro incorrecto', 'Factura registrada contra la contraparte intragrupo o cuenta equivocada', 'Reclasificar a la contraparte/cuenta correcta']] }
      },
      {
        heading: 'El proceso de conciliación y confirmación',
        paragraphs: [
          'Los grupos de buenas prácticas no descubren los descuadres en la consolidación — los previenen con un ritmo mensual. Cada par de contrapartes intercambia un extracto de saldos intragrupo; cada parte confirma o disputa cada línea; las disputas van a un responsable nombrado con un plazo; y el equipo de finanzas del grupo sigue la antigüedad de las partidas sin conciliar como sigue las cuentas a cobrar vencidas.',
          'Dos decisiones de diseño importan. Primera, un único plan contable intragrupo y códigos de contraparte en todo el grupo, para que una factura no pueda registrarse contra la contraparte equivocada por accidente. Segunda, segregación: la persona que confirma el saldo de la empresa B no debe ser la misma que registró las cuentas a pagar de la empresa B. Lo intragrupo es un canal clásico de fraude — las ventas ficticias a una filial inflan tanto los ingresos como las cuentas a cobrar — y la confirmación independiente es el control que lo detecta.'
        ],
        bullets: ['Extractos intragrupo mensuales intercambiados y confirmados por ambas partes.', 'Códigos de contraparte estándar y un único plan contable intragrupo en todo el grupo.', 'Responsables nombrados y plazos para cada partida disputada; antigüedad seguida centralmente.', 'Confirmación hecha con independencia de las personas que registraron las transacciones.']
      },
      {
        heading: 'Resolver el caso: registrar la corrección',
        paragraphs: [
          'De vuelta a nuestro caso: la investigación encontró la factura no registrada de $5,000 — A facturó a B por el soporte IT de diciembre, y B nunca la registró. La corrección pertenece a los libros de B, porque la cuenta a pagar de B está infravalorada. B registra el gasto y el pasivo; A no cambia nada. Tras registrar, la cuenta a pagar intragrupo de B a A es $150,000, coincidiendo con la cuenta a cobrar de A, y la consolidación puede proceder.',
          'Nótese lo que no se hizo: no se registró un ajuste tapón de $5,000 a una cuenta de diferencias de consolidación, no se ajustó la cuenta a cobrar de A a $145,000 para forzar la coincidencia, y no se neteó nada. Las correcciones van a la entidad cuyos libros están mal, con la documentación justificativa adecuada — la factura, en este caso — adjunta al asiento.'
        ],
        journal: {
          transaction: 'La empresa B registra la factura no registrada INV-2291 ($5,000 de soporte IT, diciembre) de la empresa A',
          lines: [
            { account: 'Gasto de soporte IT', dr: 5000, cr: null },
            { account: 'Cuenta a pagar intragrupo — Empresa A', dr: null, cr: 5000 }
          ],
          narration: 'La cuenta a pagar de B estaba infravalorada: la factura existía en el libro de A pero B nunca la registró. Tras este asiento ambas partes coinciden en $150,000.'
        },
        impact: { pl: 'El resultado de la empresa B cae $5,000 (el gasto pertenece a diciembre).', bs: 'La cuenta a pagar intragrupo de B sube a $150,000, coincidiendo con la cuenta a cobrar de A; el fondo de maniobra del grupo queda correctamente expresado.', cf: 'Aún sin efecto en efectivo — el efectivo se mueve cuando B paga la factura.' }
      }
    ],
    mistakes: [
      'Tapar la diferencia en una cuenta de suspense o de "diferencias intragrupo" en lugar de investigar la causa.',
      'Forzar la coincidencia ajustando la parte correcta a la cifra de la parte equivocada.',
      'Registrar las diferencias de cambio en el saldo intragrupo en lugar de en ganancias/pérdidas por diferencias de cambio.',
      'Confirmar saldos verbalmente o por email sin intercambiar extractos detallados.',
      'Dejar que pequeñas diferencias recurrentes se arrastren — se acumulan y se vuelven inauditables.',
      'Compensar cuentas a cobrar intragrupo contra cuentas a pagar en los estados financieros separados sin derecho legal de compensación.'
    ],
    interviewQA: [
      { q: 'La cuenta a cobrar intragrupo de la empresa A es $150,000 pero la cuenta a pagar de la empresa B es $145,000. Explicar la investigación paso a paso.', a: 'Primero obtengo ambos submayores detallados — las facturas de A a B y las facturas de B desde A — con números de documento, fechas, importes y monedas. Después concilio transacción por transacción para aislar las partidas sin conciliar. Para cada una diagnostico la causa: factura no registrada, diferencia temporal, efectivo en tránsito, diferencias de cambio, o registro incorrecto. En este caso encontraría la factura de $5,000 de A no registrada en los libros de B, por lo que B registra el gasto y la cuenta a pagar. Nunca tapo la diferencia, y reejecuto la conciliación para confirmar que ambas partes coinciden en $150,000 antes de la consolidación.' },
      { q: '¿Cuáles son las causas más comunes de descuadres intragrupo?', a: 'Cinco clásicas: una transacción registrada por una parte y no por la otra (factura no registrada); diferencias temporales donde ambas partes registran en periodos diferentes; efectivo en tránsito al cierre del periodo; diferencias de cambio donde la moneda de transacción coincide pero la conversión difiere; y registro incorrecto contra el código de contraparte o cuenta equivocada. Las diferencias temporales y el efectivo en tránsito se autoresuelven y necesitan documentación, no asientos; las demás necesitan correcciones en los libros de la entidad correcta.' },
      { q: '¿Cómo se evita que las diferencias intragrupo bloqueen el cierre?', a: 'Con un ritmo mensual, no una carrera de fin de año: códigos de contraparte estandarizados y un plan contable intragrupo, intercambio mensual de extractos y confirmación formal entre contrapartes, responsables nombrados con plazos para las disputas, y seguimiento centralizado de la antigüedad de partidas sin conciliar. La confirmación debe ser independiente de las personas que registran las transacciones, porque lo intragrupo es un canal conocido de fraude — las ventas ficticias a una filial inflan ingresos y cuentas a cobrar simultáneamente.' }
    ],
    quiz: [
      { question: '¿Por qué los saldos intragrupo deben coincidir antes de registrar las eliminaciones de consolidación?', options: ['La NIIF 10 prohíbe cualquier eliminación cuando los saldos difieren más del 1 %', 'Los auditores se niegan a auditar grupos con transacciones intragrupo', 'Las eliminaciones asumen imágenes espejo — un descuadre significa un error en los libros de alguien que debe encontrarse primero', 'El software de consolidación no puede procesar entradas descuadradas'], answer: 2, explanation: 'Una eliminación cancela la cuenta a cobrar de A contra la cuenta a pagar de B. Si difieren, la diferencia es un error real (factura no registrada, diferencias de cambio, registro erróneo) en los estados financieros separados de alguien — taparlo enterraría el error.', difficulty: 'Foundation', topic: 'Intercompany Basics', skill: 'Consolidation' },
      { question: 'La cuenta a cobrar de A a B es $150,000; la cuenta a pagar de B a A es $145,000. ¿Cuál es el primer paso correcto?', options: ['Registrar un ajuste de $5,000 para que los saldos coincidan', 'Obtener ambos submayores detallados y conciliar transacción por transacción para aislar las partidas sin conciliar', 'Pedir a B que reduzca su cuenta a pagar a $145,000 y seguir adelante', 'Eliminar $145,000 y dejar los $5,000 en una cuenta de suspense'], answer: 1, explanation: 'La investigación empieza con evidencia: libros detallados de ambas partes, conciliados línea a línea. Los ajustes solo llegan después de diagnosticar la causa — nunca antes.', difficulty: 'Intermediate', topic: 'Investigation', skill: 'Consolidation' },
      { question: 'La conciliación encuentra que A registró una factura de $5,000 que B nunca registró. La resolución correcta es:', options: ['A registra Debe Gasto $5,000 / Haber Cuenta a cobrar intragrupo — B $5,000', 'Registrar un ajuste tapón de $5,000 a reservas de consolidación', 'Reducir la cuenta a cobrar de A a $145,000 para forzar la coincidencia', 'B registra Debe Gasto $5,000 / Haber Cuenta a pagar intragrupo — A $5,000'], answer: 3, explanation: 'Los libros de B son los equivocados — su cuenta a pagar está infravalorada. La corrección pertenece a B: reconocer el gasto y el pasivo. A no cambia nada.', difficulty: 'Intermediate', topic: 'Corrections', skill: 'Consolidation' },
      { question: 'A paga a B $20,000 el 31 de diciembre; el extracto bancario de B muestra el cobro el 3 de enero. Esto es:', options: ['Efectivo en tránsito — una diferencia temporal que se autoresuelve; documentarla, no registrarla', 'Un error que exige que B registre el efectivo en diciembre', 'Un error que exige que A revierta el pago', 'Evidencia de fraude que debe informarse inmediatamente'], answer: 0, explanation: 'El efectivo en tránsito es la diferencia temporal clásica: ambas partes son correctas en su propio periodo. Documentarlo como partida conciliatoria y confirmar el cobro — sin asiento necesario.', difficulty: 'Intermediate', topic: 'Timing Differences', skill: 'Month-End Closing' },
      { question: 'A (entidad en euros) factura a B (entidad en dólares) €10,000. Ambas registran €10,000, pero tras la conversión los saldos difieren. La causa y la corrección son:', options: ['Una factura no registrada — una parte debe registrar la transacción', 'Movimiento de diferencias de cambio — cada parte registra su ganancia/pérdida de cambio usando una fuente de tipo acordada', 'Efectivo en tránsito — esperar al siguiente periodo', 'Código de contraparte incorrecto — reclasificar la factura'], answer: 1, explanation: 'La moneda de transacción coincide, por lo que nada falta — la diferencia proviene de convertir a tipos o fechas diferentes. Cada entidad reconoce su propia ganancia o pérdida de cambio; los grupos previenen la recurrencia acordando la fuente del tipo y el momento.', difficulty: 'Intermediate', topic: 'FX Differences', skill: 'Consolidation' },
      { question: 'Una factura de A fue registrada por B contra la contraparte intragrupo "Empresa C" en lugar de "Empresa A". La corrección es:', options: ['Reclasificar la cuenta a pagar de C a A', 'Registrar una nueva factura de A', 'Dar de baja la cuenta a pagar como ganancia', 'Dejarla — se netea a cero en la consolidación'], answer: 0, explanation: 'El registro incorrecto se corrige reclasificando al código de contraparte correcto. No se netea a cero: la cuenta a cobrar de A quedaría sin conciliar y C mostraría una cuenta a pagar fantasma.', difficulty: 'Foundation', topic: 'Incorrect Posting', skill: 'Consolidation' },
      { question: 'A emite una nota de abono de $3,000 a B, registrada por A pero nunca registrada por B. Como resultado:', options: ['La cuenta a cobrar de A a B está sobrevalorada en $3,000', 'Ambos saldos son correctos', 'La cuenta a pagar de B a A está sobrevalorada en $3,000', 'Los ingresos del grupo están sobrevalorados en $3,000'], answer: 2, explanation: 'A redujo su cuenta a cobrar vía la nota de abono; B, al no tenerla, sigue mostrando la cuenta a pagar más alta. B debe registrar Debe Cuenta a pagar intragrupo — A $3,000 / Haber la cuenta de gasto o existencias correspondiente.', difficulty: 'Intermediate', topic: 'Credit Notes', skill: 'Consolidation' },
      { question: '¿Qué control previene mejor que los descuadres intragrupo bloqueen el cierre?', options: ['Consolidar antes de conciliar lo intragrupo', 'Permitir a cada entidad elegir sus propios códigos de contraparte', 'Que el empleado de cuentas a pagar confirme los saldos que registró', 'Intercambio mensual de extractos con confirmación formal por ambas contrapartes'], answer: 3, explanation: 'Un ritmo mensual de intercambio y confirmación detecta las diferencias cuando son pequeñas y recientes. La confirmación debe ser independiente del que registró — la autoconfirmación no es control en absoluto.', difficulty: 'Intermediate', topic: 'Investigation', skill: 'Month-End Closing' },
      { question: 'Una diferencia intragrupo inexplicada de $5,000 al cierre del ejercicio debe:', options: ['Taparse a resultados para que la consolidación cuadre', 'Investigarse hasta encontrar la causa y corregirse en los libros de la entidad correcta', 'Netearse contra las transacciones intragrupo del mes siguiente', 'Revelarse en las notas sin más acción'], answer: 1, explanation: 'Las diferencias inexplicadas nunca se tapan, se netean, ni se despachan solo con revelación. Cada una es un error (o fraude potencial) en los libros de alguien y debe resolverse con una corrección justificada.', difficulty: 'Foundation', topic: 'Investigation', skill: 'Consolidation' }
    ]
  }
];
